### ISSUE TITLE
Cannot retrieve genome from accession / BioProject

### ISSUE THREAD

**Issue by muffato** [ncbi/datasets#100]
Hello,

I want to download the summary (as JSON) of this assembly [GCA_927399515.1](https://www.ncbi.nlm.nih.gov/assembly/GCA_927399515.1) ("gfLaeSulp1.1") with `datasets` but it's not able to find it from its assembly and BioProject accessions
```
$ datasets version
13.1.0
$ datasets summary genome accession GCA_927399515.1
{"total_count": 0}
$ datasets summary genome accession PRJEB49995
Error: No genomes found for one or more of the requested accessions

Usage
(...)
```
The same command works with the alternate haplotype [GCA_927399535.1](https://www.ncbi.nlm.nih.gov/assembly/GCA_927399535.1) ("gfLaeSulp1.1 alternate haplotype"):
```
$ datasets summary genome accession GCA_927399535.1 | jq -r '.assemblies [] | .assembly.assembly_accession'
GCA_927399535.1
$ datasets summary genome accession PRJEB49996 | jq -r '.assemblies [] | .assembly.assembly_accession'
GCA_927399535.1
```

If I use the species-level BioProject [PRJEB47319](https://www.ncbi.nlm.nih.gov/bioproject/760425) it can only find the alternative haplotype as well, despite both assemblies being listed on the [website](https://www.ncbi.nlm.nih.gov/assembly?LinkName=bioproject_assembly_all&from_uid=760425):
```
$ datasets summary genome accession PRJEB47319 | jq -r '.assemblies [] | .assembly.assembly_accession'
GCA_927399535.1
```
For all other species, like [_Vanessa cardui_ PRJEB42945](https://www.ncbi.nlm.nih.gov/bioproject/700943) I can get both
```
$ datasets summary genome accession PRJEB42945 | jq -r '.assemblies [] | .assembly.assembly_accession'
GCA_905220365.1
GCA_905220355.1
```

**Comment by ericcox1** [comment]
Hi Matthieu, 

Thanks for your feedback. This is most likely a timing issue. [GCA_927399515.1](https://www.ncbi.nlm.nih.gov/assembly/GCA_927399515.1) was submitted on February 3, 2022 and hasn't yet been copied to Datasets. We'll try to get the data copied to Datasets ASAP and I'll comment on this thread when it's available.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by ericcox1** [comment]
Hi Matthieu,

We updated our genome data today and [GCA_927399515.1](https://www.ncbi.nlm.nih.gov/assembly/GCA_927399515.1) ("gfLaeSulp1.1") is now available in Datasets.

Note that if you query by species-level BioProject, you can now get both haplotypes and their corresponding assembly-level BioProjects:
```
datasets summary genome accession PRJEB47319 | jq -r '.assemblies[].assembly | [.assembly_accession,.org.sci_name,.bioproject_lineages[].bioprojects[0].accession,.display_name] | @tsv'
GCA_927399515.1	Laetiporus sulphureus	PRJEB49995	gfLaeSulp1.1
GCA_927399535.1	Laetiporus sulphureus	PRJEB49996	gfLaeSulp1.1 alternate haplotype
```
Thanks for your patience.

Best,
Eric

**Comment by muffato** [comment]
Thank you very much Eric. I can confirm that I could pick it up on my end.

Related to "*We updated our genome data today and [GCA_927399515.1](https://www.ncbi.nlm.nih.gov/assembly/GCA_927399515.1) ("gfLaeSulp1.1") is now available in Datasets.*"
I've been noticing that indeed: a large number of assemblies were just released since yesterday. Can you confirm how frequently the Datasets database gets updated ? Is there a document somewhere that explains the release protocol / schedule ?
est,
Matthieu

**Comment by ericcox1** [comment]
Hi Matthieu,

In general, we update the genome data once per week, but due to active development of the Datasets resource, updates may be irregular.
At this time, the release schedule is undocumented. 

Best,
Eric

**Comment by muffato** [comment]
Great, thanks for the clarification 👍🏼 

Best,
Matthieu
