### ISSUE TITLE
13.4.0 release

### ISSUE THREAD

**Issue by muffato** [ncbi/datasets#103]
Hello,

`datasets` tells me that there is a new version available (13.4.0) but the advised URL has v13.3.0
```
$ wget --no-cache https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets
--2022-03-04 12:08:15--  https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.7, 130.14.250.11, 2607:f220:41e:250::11, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15080579 (14M)
Saving to: ‘datasets’

datasets                                 100%[===============================================================================>]  14.38M  15.1MB/s    in 1.0s    

2022-03-04 12:08:16 (15.1 MB/s) - ‘datasets’ saved [15080579/15080579]

$ chmod +x datasets 
$ ./datasets version
13.3.0
New version of client (13.4.0) available at https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets
```

I'd like to confirm what the latest version is, and where it is available.

Best regards,
Matthieu

**Comment by mtntsuchiya** [comment]
Hi Matthieu,
Thanks for contacting us.

There was an issue with our internal update system, but it's all working now. The latest version is 13.4.0 and you should be able to retrieve it using your command above. 

Please let us know if you encounter any other issues.
Thanks again,
Mirian

Mirian T. N. Tsuchiya, Ph.D.
Bioinformatics Data Wrangler (contractor)
NCBI Datasets (NCBI/NLM/NIH)
(she/her/hers)

**Comment by muffato** [comment]
It now worked, thank you !
