### ISSUE TITLE
Update of Galaxy tool

### ISSUE THREAD

**Issue by bernt-matthias** [ncbi/datasets#106]
In https://github.com/galaxyproject/tools-iuc/pull/4453 we try to update the Galaxy tool of `ncbi datasets`. 

Wondering if there are any changes necessary to the Galaxy tool. If I understand the diff then in some cases the possibility to obtain `gbff` has been removed...

**Comment by olearyna** [comment]
Hi Mattias,

Yes, the current version of `ncbi datasets` (13.5.1) removes the option for the `.gbff ` file in the virus data package.

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets [contractor]
National Center for Biotechnology Information, NLM, NIH, DHHS [Contractor]
Building 45 Room 6As.41
Bethesda, MD 20892
tel 301.402.1808

**Comment by bernt-matthias** [comment]
Thanks for the clarification
