### ISSUE TITLE
"datasets download genome accession" command gives error

### ISSUE THREAD

**Issue by sanyalab** [ncbi/datasets#110]
Hello,

My Commands and the error I get is as below

Example 1:
`datasets download genome accession GCF_002575655.2 --exclude-genomic-cds --exclude-gff3 --exclude-protein --exclude-rna --dehydrated --filename Aegilops_tauschii.zip`
`Error: Input accessions not specified`

Example 2:
`datasets download genome accession GCF_000710875.1 --exclude-genomic-cds --exclude-gff3 --exclude-protein --exclude-rna --dehydrated --filename Capsicum_annuum.zip`
`Error: Input accessions not specified`

Example 3:
`datasets download genome accession GCF_000001405.39 --dehydrated --filename human_GRCh38_dataset.zip`
`Error: Input accessions not specified`

I have installed ncbi_datasets using conda, and version is 13.10.0. Please advice

Thanks
Abhijit

**Comment by sanyalab** [comment]
Sure,

`(ncbi_datasets) lxjh634:/home/sanyalab$ datasets version`
`13.10.0`

The above command does not seem to exit after displaying the output version. I am having to kill it using `cntrl-c`

Operating system is Linux Red hat
`(ncbi_datasets) lxjh634:/home/sanyalab$ cat /proc/version`
`Linux version 3.10.0-514.26.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Jul 4 15:04:05 UTC 2017`

**Comment by mtntsuchiya** [comment]
Thanks for sharing it. Could try one more thing: `datasets version --debug` and paste the output here?
Thanks again!
