### ISSUE TITLE
issue with graphical nsp13-nps16 of SARS-CoV-2

### ISSUE THREAD

**Issue by carlottaolivero** [ncbi/datasets#129]
There is an issue with the graphical genomic tool of SARS-CoV-2 relative to nsp16. 
It should starts at nt 20659, but the graph shows nsp13 instead. 
nsp13 is correctly shown at nt 16237.
Attached the picture relative to the issue
![nsp13-16](https://user-images.githubusercontent.com/65721475/172414242-bbec3db7-a75f-4e97-a113-f7cbe3006ddf.jpg)

**Comment by olearyna** [comment]
Hi, 

Thanks for contacting Datasets. Pfam has recently revised the name of this model, and it will take a while for us to reflect that in CDD. Unfortunately the corresponding domain model that has been curated in-house is outscored by the Pfam alignment in a number of cases. We’ll attempt to do a one-off patch in the next CDD release

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS [Contractor]
Building 45 Room 6As.41
Bethesda, MD 20892
tel 301.402.1808

**Comment by carlottaolivero** [comment]
Hi,
I have checked and the portion of nsp16 is still named NSP13 on the
graphical.
Is there a reason why you close the issue #129
<https://github.com/ncbi/datasets/issues/129> ?
Thank you,
Carlotta

**Comment by olearyna** [comment]
Hi Carlotta, apologies, I'm re-opening the issue while we wait for the CDD release.

**Comment by carlottaolivero** [comment]
Thank you very much

**Comment by syntheticgio** [comment]
This has been reported to the relevant team, although unfortunately we don't have direct access to progress on it.  I'm going to close this since this isn't specifically related this source code.
