### ISSUE TITLE
Gateway Error (400 Bad Request) 

### ISSUE THREAD

**Issue by eamiddlebrook** [ncbi/datasets#133]
Hi all,

When trying to fetch assemblies at my institution or through its proxy, I get a "Bad Request" error. From home the same command on the same comp/environment works just fine. 
```
~$ taxon=234
~$ datasets download genome taxon $taxon --dehydrated --exclude-genomic-cds --exclude-gff3 --exclude-protein --exclude-rna
Error: [gateway] Gateway Error (400 Bad Request)
```

Is there a way for the proxy settings to corrupt the https request?
the proxies for my institution are all http sites, could this be messing up the request? Other https requests seem to go through just fine...

Awesome tool BTW!

Thanks!
Earl

**Comment by mtntsuchiya** [comment]
Hi Earl,
Thank you for using NCBI Datasets and for contacting us. We're glad to hear you like our tool :) 
I'm sorry your finding issue when trying to download genomes. To help us troubleshoot, could you please include the flag `--debug` and share the ncbi-phid? 

Thanks again, and I look forward to hearing back from you.
Best,
Mirian

Mirian T. N. Tsuchiya, Ph.D.
Bioinformatics Data Wrangler (contractor)
NCBI Datasets (NCBI/NLM/NIH)
(she/her/hers)

**Comment by eamiddlebrook** [comment]
Mirian,

Here is the debug output:
```
$ datasets download genome taxon $taxon --dehydrated --exclude-genomic-cds --exclude-gff3 --exclude-protein --exclude-rna --debug
2022/06/14 09:00:58
POST //genome HTTP/1.1
Host: proxyserver.internal:443
User-Agent: OpenAPI-Generator/13.5.1/go
Content-Length: 169
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

{"filters":{"assembly_source":"all","has_annotation":false,"reference_only":false},"page_size":1000,"returned_content":"ASSM_ACC","tax_exact_match":false,"taxon":"234"}

2022/06/14 09:01:09
HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 3296
Content-Language: en
Content-Type: text/html;charset=utf-8
Date: Tue, 14 Jun 2022 15:01:09 GMT
Mime-Version: 1.0
Server: squid
Vary: Accept-Language
Via: 1.1 proxyserver.internal (squid)
X-Cache: MISS from proxyserver.internal
X-Cache-Lookup: NONE from proxyserver.internal:443
X-Squid-Error: ERR_INVALID_URL 0 
```

Not sure what the "ncbi-phid". If it isn't in the above output, is there a command to run to get it?

Thanks so much for the help,
earl

**Comment by mtntsuchiya** [comment]
Hi Earl,
Thanks for the info. 

The `--debug` flag was the option to retrieve that information, but it didn't work in this case.
We see that the proxy has re-written the URL from `/v1/datasets/genome` to `//genome` .  Without knowing the details of the proxy, it is hard to determine why that is the case.  Maybe the proxy maintainer from your institution can shed some light on this?

Thanks,
Mirian
