### ISSUE TITLE
Compression issue

### ISSUE THREAD

**Issue by night-fury-web** [ncbi/datasets#134]
When I downloaded virus genome dataset using datasets CLI, it's around 4GB in zip while the content is 15GB.
If I decompress the data using winrar and compress extracted directory, the compressed file is about 150M which is very surprising.

Is there any loss in my new compressed file?

Any advice is appreciated.

**Comment by whlavina** [comment]
Thank you for reaching out with your concern.

The compression results you see are expected, as the virus data includes many highly similar sequences. We are favoring convenience and using popular, industry standard compression tools. The zip/gzip compression algorithm is unable to take full advantage of the redundancy. Depending on the nature of the sequence data, other algorithms may perform substantially better.

If you are interested in the topic, here are some relevant citations to get you started:
* [Is it time to replace gzip? Comparison of modern compressors for molecular sequence databases](https://www.biorxiv.org/content/10.1101/642553v1.full.pdf)
* [Vertical lossless genomic data compression tools for assembled genomes: A systematic literature review](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0232942)
* [Sequence Compression Benchmark](http://kirr.dyndns.org/sequence-compression-benchmark/)
