### ISSUE TITLE
question on downloading SARS-CoV-2 assemblies

### ISSUE THREAD

**Issue by kapsakcj** [ncbi/datasets#148]
Hi, I would like to download a few recently submitted SARS-CoV-2 (Omicron and decendent lineages) assemblies for testing purposes, however I'm having trouble finding the correct accession to use and/or might be using the tool incorrectly. 

I see in [the documentation that usually accessions begin with `GCA_`or `GCF_`](https://www.ncbi.nlm.nih.gov/datasets/docs/v1/how-tos/genomes/download-genome/) but the assemblies that I'm interested in begin with `ON`

For example:

```bash
$ datasets download genome accession --filename ON924087.1.zip ON924087
Error: invalid or unsupported assembly accession: ON924087
```

https://www.ncbi.nlm.nih.gov/nuccore/ON924087.1/

Is it possible to download the assembly FASTA for this sample using this tool? Is there a corresponding `GCA_` accession for this sample that I'm not seeing?

I have really enjoyed this `datasets` tool thus far and am interested in learning how to use it better. Thanks for all of your efforts into developing this tool.

**Comment by mtntsuchiya** [comment]
Hi kapsakcj,
Thank you for using NCBI Datasets and contacting us. 

You can download virus genomes by accession with our `virus` subcommand. Like this:

```
datasets download virus genome accession ON924087.1 --filename ON924087.1.zip
```

So, you need to add `virus` before `genome` and the accession number needs to be right after `accession`. If youplace it in the end of the command like you did, you will end up downloading an empty data package. 

Thanks again for using NCBI Datasets and please feel free to contact us if you have any other issues.

Best,
Mirian

Mirian T. N. Tsuchiya, Ph.D.
Bioinformatics Data Wrangler (contractor)
NCBI Datasets (NCBI/NLM/NIH)
(she/her/hers)

**Comment by kapsakcj** [comment]
Perfect, that worked! Thank you for your help!

P.S. I love your job title 😄 
>Bioinformatics Data Wrangler (contractor)

**Comment by mtntsuchiya** [comment]
Glad to help! 
[and yes, it's a fun name 😄 )
