### ISSUE TITLE
Please Add License

### ISSUE THREAD

**Issue by erinyoung** [ncbi/datasets#154]
I noticed that this repo doesn't have a license. I would like to use this tool. I think it is being developed under something like that for [SRA-tools](https://github.com/ncbi/sra-tools/blob/master/LICENSE), but would love confirmation about this.

**Comment by olearyna** [comment]
Hi Erin,

Thanks for contacting us!
Here is the link to the Public Domain License https://github.com/ncbi/datasets/blob/master/pkgs/ncbi-datasets-cli/LICENSE.md. Sorry, it's not that easy to find. We will duplicate it to our root directory.

Thanks
Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS [Contractor]
Building 45 Room 6As.41
Bethesda, MD 20892
tel 301.402.1808

**Comment by erinyoung** [comment]
Perfect! Thank you!!!
