### ISSUE TITLE
Unable to download anything but fna files

### ISSUE THREAD

**Issue by chasemc** [ncbi/datasets#173]
datasets version:
3.42.1

command:
`datasets download genome accession GCA_000302695.1 --include-gbff`

Results:
```
├── ncbi_dataset
│   └── data
│       ├── assembly_data_report.jsonl
│       ├── dataset_catalog.json
│       └── GCA_000302695.1
│           ├── GCA_000302695.1_LSJC7_1.0_genomic.fna
│           └── sequence_report.jsonl
└── README.md
```

**Comment by mtntsuchiya** [comment]
Hi chasemc,
Thanks for letting us know about this issue and I'm sorry about it. 

I was able to replicate the error and our team is looking for a solution. In the meantime, you can find the gbff file for that assembly in our FTP site: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/302/695/GCA_000302695.1_LSJC7_1.0/GCA_000302695.1_LSJC7_1.0_genomic.gbff.gz. You can use `wget` to retrieve the file:

`wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/302/695/GCA_000302695.1_LSJC7_1.0/GCA_000302695.1_LSJC7_1.0_genomic.gbff.gz` 

We'll keep you posted on the solution of this issue.

Thanks again, 

Mirian T. N. Tsuchiya, Ph.D.
Bioinformatics Data Wrangler (contractor)
NCBI Datasets (NCBI/NLM/NIH)
(she/her/hers)

**Comment by chasemc** [comment]
Sorry to ask here, but where should we report bugs in the online interfaces?

**Comment by ericcox1** [comment]
Hi Chase,

Feel free to open a new issue here on our GitHub page to report any bugs in our online (web) interfaces, CLI tools, or API.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by chasemc** [comment]
> Hi Chase,
> 
> Feel free to open a new issue here on our GitHub page to report any bugs in our online (web) interfaces, CLI tools, or API.
> 
> Best, Eric
> 
> Eric Cox, PhD [Contractor] (he/him/his) NCBI Datasets Sequence Enhancements, Tools and Delivery (SeqPlus) NIH/NLM/NCBI [eric.cox@nih.gov](mailto:eric.cox@nih.gov)

Thanks, the online interface bug seems to have mysteriously resolved but I'll keep that in mind

**Comment by chasemc** [comment]
@mtntsuchiya I need to selectively download data for a large number of genomes, this was only a minimal example. I'll wait for now and concoct something with eutils if I need to

**Comment by ericcox1** [comment]
Hi @chasemc,

We have made a decision not to provide gbff files for unannotated genomes through the NCBI Datasets interfaces. For example, the gbff file is not available for the unannotated GenBank assembly GCA_000302695.1, but the gbff file _is_ available for the RefSeq copy GCF_000302695.1.

We're happy to get your feedback on this policy.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
