### ISSUE TITLE
rationale behind transcript accession requested and returned for gene

### ISSUE THREAD

**Issue by csgenomics-admin** [ncbi/datasets#180]
Hi Datasets team,

I've started making some GET requests from a list of transcript accession IDs using the v13 API REST tool. The tool is working great, but I've been curious what sorts of different error or warning messages my requests might be generating. Thankfully, there are just a handful of warning messages and no errors in my input list. However, I'm confused as to why certain transcript accession IDs that I submit are being substituted with a __lower__ version of the same base transcript ID.

For example...
```
curl -X GET "https://api.ncbi.nlm.nih.gov/datasets/v1/gene/accession/NM_004081.7" \
-H "Accept: application/json"
```
... will return a .json with this information (which I've truncated) like below. What's curious to me is the fact that I requested an accession ID (`NM_004081.7`) that appears to be two versions newer than what is returned (`NM_004081.5`) by the API:
```
{"genes":
  [
    {"warnings":
         [{"gene_warning_code":"ACCESSION_VERSION_MISMATCH", 
           "reason":"The accession.version you requested is no longer current or otherwise unrecognized.", 
           "message":"The current accession.version will be returned.", 
           "replaced_id":{"requested":"NM_004081.7", "returned":"NM_004081.5"}}],
```

What's confusing me is that this accession ID I'm submitting appears valid and current, (https://ncbi.nlm.nih.gov/nuccore/NM_004081.7), whereas the one returned by NCBI Datasets was updated as of August 2020. I've seen this behavior across several other transcripts (another example: input `NM_004678.3` returns one version lower, `NM_004678.2` - in this case, that lower version was bumped up in May 2019). 

Maybe there is a very important reason why the less-than-current version being returned by Datasets is necessary? In thinking about what's stated in the `reason` and `message` responses, perhaps what Datasets thinks is current doesn't necessarily match what https://ncbi.nlm.nih.gov/nuccore thinks is most current?

Looking forward to your thoughts

**Comment by ericcox1** [comment]
Hi csgenomics-admin,

Thanks for your feedback. Thanks to your detailed examples, we found a bug in the way that we were copying data into Datasets. We have now updated our gene data and the older transcript accessions, including `NM_004081.5` and `NM_004678.2`, have been removed.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
