### ISSUE TITLE
the source files are not available since 14.0.0?

### ISSUE THREAD

**Issue by hubutui** [ncbi/datasets#181]
The source code used to be https://github.com/ncbi/datasets/tree/release/13.43.2/pkgs/ncbi-datasets-cli, but it not there anymore.

**Comment by olearyna** [comment]
Hi hubutui,

Thanks for contacting us! We no longer publish the source code for our command line tools on GitHub. You can access the binary through Conda or the GitHub release notes page. Please let us know if we can help with any other issues.

Thanks,

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS [Contractor]
Building 45 Room 6As.41
Bethesda, MD 20892
