### ISSUE TITLE
finding orthologs

### ISSUE THREAD

**Issue by zachsebo** [ncbi/datasets#185]
Hi,

Thanks for making this tool. it's the best orthologous gene mapping tool I've found.  However, i have noticed that many orthologous genes are not identified when mapping between humans and drosophila for example.  this is true whether I use gene-id, accession, or symbol. for example:

datasets download gene symbol ATM --ortholog 9606,7227

This command doesn't return tefu, which is the drosophila ortholog of ATM. 

Any efforts to improve this such would be greatly appreciated.

**Comment by olearyna** [comment]
Hi zachsebo

Thanks for contacting us and I'm glad the tool is working out for you! Unfortunately, we don't calculate ortholog sets between human and drosophila. We have a vertebrate ortholog set that identifies 1:1 orthologs vs human using a combination of BLAST comparisons and local synteny. More recently, we added an insect ortholog set which identifies orthologs in >100 insects compared to _Drosophila melanogaster_. We are currently exploring methods to expand our ortholog calculations as a part of the [Comparative Genomics Resource](https://www.ncbi.nlm.nih.gov/comparative-genomics-resource/) initiative. We'll keep you updated as our improvements evolve. 

All the best,
Nuala

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS [Contractor]
Building 45 Room 6As.41
Bethesda, MD 20892
tel 301.402.1808
