### ISSUE TITLE
ApiTypeError

### ISSUE THREAD

**Issue by AmirUCR** [ncbi/datasets#186]
Dear NCBI Team,

I'm trying to use the Python package installed from pip `pip install --upgrade ncbi-datasets-pylib`. When I run the example Python code from [here](https://www.ncbi.nlm.nih.gov/datasets/docs/v1/how-tos/genomes/get-genome-metadata/) I get the following error:

`File "/home/user/miniconda3/envs/ncbi_datasets/lib/python3.7/site-packages/ncbi/datasets/openapi/model_utils.py", line 1449, in attempt_convert_item
    key_type=key_type)
ncbi.datasets.openapi.exceptions.ApiTypeError: Invalid type for variable 'page_token'. Required value type is str and passed type was NoneType at ['page_token']`

I tried the script with the latest ncbi-datasets-pylib version as well as version 13 and 12.22.1 -- I tried Python versions 3.11, 3.9, and 3.7 -- I get the same error in all cases.
Is the API broken at the moment? Thanks.

**Comment by olearyna** [comment]
Hi Amir,

Thanks for contacting us and sorry you're having problems with the Python package. We're looking into the issue and will let you know when we have a fix.

Thanks
Nuala


Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS [Contractor]
Building 45 Room 6As.41
Bethesda, MD 20892
tel 301.402.1808

**Comment by ericcox1** [comment]
Hi @AmirUCR,

Thanks for the bug report. This bug should now be fixed. 

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
