### ISSUE TITLE
`--tax-exact-match` seems not to work

### ISSUE THREAD

**Issue by bernt-matthias** [ncbi/datasets#187]
I hope this is the right place for bug reports for the NCBI datasets CLI tool.

When executing `datasets download genome taxon 4932 --include seq-report --tax-exact-match` the result still contains data for strains like `Saccharomyces cerevisiae ZTW1`.

Am I doing something wrong?

**Comment by ericcox1** [comment]
Hi M Bernt,

Thanks for opening this issue. This is a bug and we should not return genomes at the strain level when the `--tax-exact-match` flag is used. I'll post here when we have fixed this bug.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by syntheticgio** [comment]
I've moved the created ticket to the next sprint.  There will be further discussion internally at the beginning of the sprint to see if resources can be allocated to it.  I've created a sub-task to the ticket to report back here and close the issue when it has been resolved.

**Comment by ericcox1** [comment]
Hi @bernt-matthias,

Thanks for opening this issue. This bug has been fixed.

Note that using `--tax-exact-match` will now only return genomes at the species-level (Taxonomy ID: 4932) and will not return any strain-level genomes.
```
datasets download genome taxon 4932 --include none --tax-exact-match --filename yeast.zip
Collecting 1,450 genome records [================================================] 100% 1450/1450
Downloading: yeast.zip    332kB valid zip archive
Validating package files [================================================] 100% 3/3

# Use dataformat to generate a table and count the number of genomes for each TaxID
# In this case we have 1,450 genomes for TaxID 4932 and no strain-level genomes
dataformat tsv genome --package yeast.zip --fields organism-tax-id --elide-header | sort | uniq -c
   1450 4932
```

Best,
Eric
