### ISSUE TITLE
Feature Request : Representative Prokaryotic Genomes

### ISSUE THREAD

**Issue by erinyoung** [ncbi/datasets#190]
Maybe this feature already exists, and I just don't understand how to access it. 

There is a blast database that can be downloaded from NCBI that contains the representative refseq genomes for prokaryotic species (ref_prok_rep_genomes). I don't want the blast database, though, I'd like the full fasta sequence for each. I was hoping to be able to download these via datasets, but could not find how in the documentation anywhere.

**Comment by erinyoung** [comment]
For example, I would clarity on whether the following downloads all representative genomes for prokaryotes.

```
datasets download genome taxon Bacteria --reference
```

**Comment by ericcox1** [comment]
Hi Erin,

Thanks for opening this issue. The simple answer is yes, you can download the full fasta genome sequence for all representative RefSeq genomes for prokaryotic species using the command you mentioned above to get all bacteria _and also_ a second command to get the remaining prokaryotes, the archaea:
```
datasets download genome taxon bacteria --reference --filename bacteria.zip
datasets download genome taxon archaea --reference --filename archaea.zip
```
Note that `bacteria.zip` will also include 15 _reference_ genomes in addition to the _representative_ genomes (there are no _reference_ genomes for archaea to worry about). If you need to restrict the bacteria genome sequences to only the _representative_ genomes, you can try the following:
```
datasets summary genome taxon bacteria --reference --as-json-lines | \
dataformat tsv genome --fields accession,assminfo-refseq-category --elide-header | \
grep representative | \
cut -f1 > rep-genomes.tsv

datasets download genome accession --inputfile rep-genomes.tsv --filename rep-genomes.zip
```

I hope that helps. Please let me know if you have any other questions.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by erinyoung** [comment]
Perfect! Thank you!
