### ISSUE TITLE
Download error: http2: server sent GOAWAY

### ISSUE THREAD

**Issue by steffie11** [ncbi/datasets#193]
Dear developers,

I am using NCBI-datasets to download ~100 animal genomes. 

`datasets download genome accession --inputfile mammal_whole_accession.txt --include genome --filename mammal_download.zip`

After around 2.5h I recieve such error

```
Downloading: mammal_download.zip    21.2GB 2.37MB/s
[1A[2K[1A[2KCollecting 92  records [================================================] 100% 92/92
Downloading: mammal_download.zip    21.2GB 2.37MB/s
Error: Download error: http2: server sent GOAWAY and closed the connection; LastStreamID=5, ErrCode=NO_ERROR, debug="timeout"
```

I have tried multiple times but the same error occurs when downloading the zip file. Could you please help with that? Thanks a lot.

Cheers,
Huang

**Comment by bernt-matthias** [comment]
I get the same for 

```
datasets download genome taxon '8496' --reference --assembly-version latest --assembly-source refseq --include genome,gff3,gtf,seq-report --no-progressbar
```

at the same time I have no problem with 4 other taxa.

@steffie11 may I ask what kind of accessions you have in `mammal_whole_accession.txt`. I'm also trying to download a few dozed genomes and the best I came up with is looping over `datasets download genome taxon TAXID`...

**Comment by bernt-matthias** [comment]
Forgot to ask the following: Are there any limitations regarding the number of parallel downloads when using this tool?

**Comment by steffie11** [comment]
> I get the same for
> 
> ```
> datasets download genome taxon '8496' --reference --assembly-version latest --assembly-source refseq --include genome,gff3,gtf,seq-report --no-progressbar
> ```
> 
> at the same time I have no problem with 4 other taxa.
> 
> @steffie11 may I ask what kind of accessions you have in `mammal_whole_accession.txt`. I'm also trying to download a few dozed genomes and the best I came up with is looping over `datasets download genome taxon TAXID`...

Hi Bernt, what inside `mammal_whole_accession.txt` is Genbank acccesion numbers of the genomes, for example, GCA_000754665.1. You can find the accession when searching the scientific name of your taxon on https://www.ncbi.nlm.nih.gov/data-hub/genome/?taxon=9901. I prepare this plain text file so that I can batch download 100 genomes.

What insteresting is that after re-attempting several times, the download seemed successful at around 20 o'clock of Berlin time. Maybe you try with accession or at a time that the server is less crowded? 

A note to the developers: I have been using NCBI-datasets since version 13.27.0 and I never met this error before version 14. Would be nice if I get an answer from you guys thanks.

**Comment by steffie11** [comment]
Dear developers, 

Maybe you have seen my comments above that the download was successful after 4-5 attempts. I got `mammal_download.zip` downloaded, and I was able to unzip and rehydrate that. 
However there were still error messages
```
......
GCA_021442165.1_ASM2144216v1_genomic.fna  
  inflating: mammal_download/ncbi_dataset/data/GCA_021462335.1/GCA_021462335.1_ASM2146233v1_genomic.fna  
  inflating: mammal_download/ncbi_dataset/data/GCA_022079265.1/GCA_022079265.1_mLynRuf1.p_genomic.fna  
srun: error: prod-0059: task 0: Exited with exit code 2
srun: Terminating job step 20569611.1
Error: opening file 'mammal_download/ncbi_dataset/fetch.txt' for rehydration: open mammal_download/ncbi_dataset/fetch.txt: no such file or directory

Use datasets rehydrate <command> --help for detailed help about a command.

```

I checked that `mammal_download/ncbi_dataset/fetch.txt` indeed does not exist. However the rehydration seemed successful as all genomes from `mammal_whole_accession.txt` have been downloaded. I am curious about this error. Do you have an explaination for that? Thank you for the help.

Cheers,
Huang

**Comment by ericcox1** [comment]
Hi S Huang,

Thanks for opening this issue. For large downloads, such as 100 mammalian genomes, we would recommend our protocol for [large genome downloads](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), which includes the following 3 steps:
1. Download a dehydrated zip archive (using the `--dehydrated` flag)
2. Unzip the downloaded archive
3. Rehydrate the extracted zip archive

Is it possible that you omitted the `--dehydrated` flag in the first step? That would explain the missing `fetch.txt` file.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by ericcox1** [comment]
Hi M Bernt,

> I get the same for
>`datasets download genome taxon '8496' --reference --assembly-version latest --assembly-source refseq --include genome,gff3,gtf,seq-report --no-progressbar`

I was unable to reproduce the error using this command this morning. It's possible that you encountered a transient error.

I'll discuss this with our development team to see if there's anything we can do to increase the stability of our services.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by bernt-matthias** [comment]
Thanks for the prompt reply @ericcox1 

I also retried, with success. But I still see the error, now for other datasets :( 

Maybe for the broader picture. I'm working on improving the Galaxy tool for the NCBI dataset tool (https://github.com/galaxyproject/tools-iuc/tree/master/tools/ncbi_datasets). 

- Currently we are not using the dehydration + rehydration protocol that you mentioned above. I guess it would be a good idea to do this always, or are there downsides of doing this for small datasets?
- Is there a way to download the genomes for a list of taxids with `datasets download genome taxon` (analogous to provide a input file or taxon list to `datasets download genome accession`)

**Comment by ericcox1** [comment]
Hi @bernt-matthias, would you be able to meet for a brief chat on zoom sometime this week with some members of our development team so we can help you get these questions answered? Send me an email at eric.cox@nih.gov and I'll set something up.

Thanks,
Eric

**Comment by steffie11** [comment]
> Hi M Bernt,
> 
> > I get the same for
> > `datasets download genome taxon '8496' --reference --assembly-version latest --assembly-source refseq --include genome,gff3,gtf,seq-report --no-progressbar`
> 
> I was unable to reproduce the error using this command this morning. It's possible that you encountered a transient error.
> 
> I'll discuss this with our development team to see if there's anything we can do to increase the stability of our services.
> 
> Best, Eric
> 
> Eric Cox, PhD [Contractor] (he/him/his) NCBI Datasets Sequence Enhancements, Tools and Delivery (SeqPlus) NIH/NLM/NCBI [eric.cox@nih.gov](mailto:eric.cox@nih.gov)

Hi Eric, 

You are right. I forgot  `--dehydrated`. Problem solved. No more errors. Thanks a lot.

Cheers,
Huang
