### ISSUE TITLE
dataformat: write all warnings and errors to stderr

### ISSUE THREAD

**Issue by bernt-matthias** [ncbi/datasets#197]
Messages like the following should go to stderr:

```
dataformat doesn't recognize this input

For best results
1. Make sure to use --as-json-lines
2. Make sure that you're using datasets CLI v14.x

Use --force to remove this warning.
Download CLI v14.x: https://www.ncbi.nlm.nih.gov/datasets/docs/v2/download-and-instal
```

**Comment by ericcox1** [comment]
Hi @bernt-matthias, thanks for opening this issue. We are currently in the planning stages of making improvements to dataformat and I will add this to the list.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
