### ISSUE TITLE
Technical questions (changelog, sources, link stability)

### ISSUE THREAD

**Issue by bernt-matthias** [ncbi/datasets#199]
Sorry for the amount of questions from my side. Feel free to answer whenever you find the time. 

Is there is some sort of changelog for NCBI datasets? This would be pretty cool for keeping software using this tool up to date (like for instance the Galaxy tool wrappers). Alternatively is there a repository containing the actual source code?

Can the URLs in the dehydrated datasets be considered as stable? Guess this is the question I got most often from colleagues when discussing this tool. It would allow to keep only dehydrated datasets and still allow full reproducibility. This would make this tool even more awesome.

**Comment by ericcox1** [comment]
Hi @bernt-matthias,

I'll answer your questions in order.

>Is there is some sort of changelog for NCBI datasets? This would be pretty cool for keeping software using this tool up to date (like for instance the Galaxy tool wrappers). 
We don't have a changelog file per se, but we do have [release notes](https://github.com/ncbi/datasets/releases/tag/v14.5.0).

>Alternatively is there a repository containing the actual source code?
Our long-term plan is to put the CLI source code in GitHub but it is not available at the moment.

>Can the URLs in the dehydrated datasets be considered as stable?
The URLs in the `fetch.txt` file included in the dehydrated package are _not_ stable.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
