### ISSUE TITLE
md5sum for downloads

### ISSUE THREAD

**Issue by chasemc** [ncbi/datasets#206]
I downloaded a bunch of "gbff" files via the online portal and then spent a bunch of time trying to debug some errors in biopython parsin but it turned out it was caused by subtle corruption of the downloaded genome file.
Is it possible to include an md5sum file within or of the zip download, for validation?

**Comment by ericcox1** [comment]
Hi Chase,

Thanks for opening this issue. I'm sorry to hear that the genome file was corrupted. Is it possible for you to share the file with us so we could take a look at it?

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by syntheticgio** [comment]
Unable to replicate this issue.  If it happens again please feel free to open a new issue.
