### ISSUE TITLE
ortholog - one sequence per a gene

### ISSUE THREAD

**Issue by JonEilers** [ncbi/datasets#214]
Hi,
Maybe I missed it in the documentation, but is there a way to download one sequence per a gene using the command line datasets gene download orthologs tool?

**Comment by ericcox1** [comment]
Hi Jon,

We have a [tutorial](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/tutorials/ortholog-get-one-isoform/) for getting the one (longest) transcript and protein sequence per gene for an ortholog set. This involves downloading the data first using `datasets` and then using `seqtk` to extract the sequences and save them to a new file.

I hope that helps. Please let me know if you have any other questions.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
