### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by cademirch** [ncbi/datasets#217]
I'd like to cite this tool, is there a publication I can cite?

**Comment by olearyna** [comment]
Hi,

Thanks for your question about citing NCBI Datasets. We're working on a Datasets publication. For now you can cite the following: 

1. [PMID:33095870 ](https://pubmed.ncbi.nlm.nih.gov/33095870/)
2. The version of the command line tool. For example `datasets version: 14.17.0`. 
3. The command line tool [install page](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/download-and-install/)

Let me know if you have any further questions.

Regards,

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS [Contractor]

**Comment by cademirch** [comment]
Great, thank you!
