### ISSUE TITLE
request - provide docker images

### ISSUE THREAD

**Issue by kapsakcj** [ncbi/datasets#220]
Hi, Thanks for developing this wonderful resource.

I would like to include `datasets` in bioinfo pipelines that utilize containers (& cannot use conda) and wanted to request that this tool is added to the NCBI collection of docker images over on 

https://github.com/ncbi/docker

and

docker images hosted on dockerhub: https://hub.docker.com/u/ncbi

Myself and a few colleagues have been making dockerfiles available in the [StaPH-B docker-builds repository](https://github.com/StaPH-B/docker-builds) and docker images available on [dockerhub](https://hub.docker.com/r/staphb/ncbi-datasets/tags) & [quay](https://quay.io/repository/staphb/ncbi-datasets?tab=tags), but it is difficult to keep up with the frequent release cycle (a good problem to have 😄)

Is this something that could be added in the future?

Thanks,
Curtis

**Comment by olearyna** [comment]
Hi Curtis,

Thank you for contacting us! We appreciate your suggestion about adding a docker image, and we will certainly consider it for future updates. We will keep you informed about any progress.

All the best,
Nuala

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS [Contractor]
