### ISSUE TITLE
datasets summary genome accession   downloads specific accessions twice

### ISSUE THREAD

**Issue by janpb** [ncbi/datasets#225]
It appears the command `datasets summary genome accession  --report genome` fetches certain assembly accessions twice into one JSON file. After fetching specific accessions (see below), the resulting file contains two identical reports instead of the expected one.

If this is not a bug, why do I get 2 identical reports for these accessions?

Details:

- datasets version: 14.22.1

Example (attached in ZIP file): 

1. Command: 
   `datasets summary genome accession --report genome GCA_024174645.1 > GCA_024174645.1.json`
3. extracting the two reports into individual JSON files :
   - `GCA_024174645.1.report-1.json` and` GCA_024174645.1.report-2.json`
4. Comparing: diff reports no differences between these reports
    `diff <(jq --sort-keys . GCA_024174645.1.report-1.json <(jq --sort-keys . GCA_024174645.1.report-2.json)`

In contrast, the  assembly accession `GCA_025727855.1` reports only one report, as expected. 

So far, the following accessions resulted in the exact same summary report within one result (* indicates the report is attached in the ZIP file): 

GCA_024085815.1
GCA_024086825.1* 
GCA_024138005.1
GCA_024138015.1
GCA_024138025.1
GCA_024174645.1*
GCA_024222315.1
GCA_025762735.1
GCA_025762765.1
GCA_900006205.1
GCA_900006705.1
GCA_900059795.1
GCA_900067695.1
GCA_900070015.1

[ncbi-datasets-doubles.zip](https://github.com/ncbi/datasets/files/11287874/ncbi-datasets-doubles.zip)

**Comment by janpb** [comment]
Dear Nuala,

I successfully  tried the new datasets release (14.23.0) with the above accessions. The doubled reports are gone and I got one report per accession, as expected. 

thanks  for the fast reply and fix. Much appreciated. 

All the best,

Jan

**Comment by janpb** [comment]
Dear Nuala,

apparently, I was a bit too excited. While the listed accessions do work, I get now duplicate reports for these two accessions which did not cause trouble before:

- GCA_021901955.1
- GCA_021904315.1

**Comment by olearyna** [comment]
Thanks for letting us know! We're looking into it.

**Comment by olearyna** [comment]
Hi,

The latest fix is in production, thanks again for reporting this.

Nuala
