### ISSUE TITLE
Panic: runtime error when downloading datasets with Python script

### ISSUE THREAD

**Issue by NickDA225** [ncbi/datasets#240]
Hi, I am using Python to download a host of datasets with a script. I have had no issues until today when the script began outputting the error:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x90c895]`

`goroutine 1 [running]:
datasets_cli/v2/datasets.downloadData(0xaa6c51?, 0x10?, {0x0?, 0x0?}, {0xaa6c51?, 0x0?}, 0x0?)
        apps/public/Datasets/v2/datasets/datasets/Download.go:34 +0xb5
datasets_cli/v2/datasets.downloadDataForFile(0xc0000afec8?, {0xb94920?, 0xc0001ed440?}, {0xaa6c51, 0x10}, 0x0?)
        apps/public/Datasets/v2/datasets/datasets/Download.go:26 +0x15b
datasets_cli/v2/datasets.(*GeneProkDownloader).Download(0x0?)`

`apps/public/Datasets/v2/datasets/datasets/GeneDownloader.go:283 +0xa5
datasets_cli/v2/datasets.createDownloadGeneAccession.func1(0xc0001e2900?, {0xc0001f45a0?, 0x1?, 0x1?})
        apps/public/Datasets/v2/datasets/datasets/DownloadGeneAccession.go:51 +0xee
github.com/spf13/cobra.(*Command).execute(0xc0001e2900, {0xc0001f4570, 0x1, 0x1})
        external/com_github_spf13_cobra/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xfb0c60)`
        
`external/com_github_spf13_cobra/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        external/com_github_spf13_cobra/command.go:992
datasets_cli/v2/datasets.Execute()
        apps/public/Datasets/v2/datasets/datasets/root.go:486 +0x25
main.main()
        apps/public/Datasets/v2/cmd/datasets/main.go:10 +0x17`

There is no specific accession that gives rise to this issue or logic behind why it occurs. Sometimes the script will run and successfully download 3-4 datasets before this issue arrises, often times it only manages to download 1 before the error is given. I am using Python to execute the datasets.exe with the command:

`subprocess.check_call('datasets download gene accession ' + accession_id, cwd=work_dir)`

I initially thought it was due to the fact that perhaps the script was sending too many requests at once, so I included a wait time  of 0.5s between each download but this did not resolve the issue. Any ideas? 

Thanks!

**edit**: Just to add some context further I have been playing around since and found that when this issue occurs it seems to then repeatedly occur then after, and even if I manually execute the datasets command in command prompt (after it has occurred in the python script) it returns the same error several times. However if I wait then repeatedly execute the command in command prompt it eventually after 3-4+ tries successfully downloads the dataset.

**Comment by ericcox1** [comment]
Hi @NickDA225,

Thanks for opening this issue. We'll need a little bit more information before we can start debugging this. Could you please share the following with us:
1. Some example accessions that you tried when you saw the error
2. A `Ncbi-Phid` value if available (these are often shown with the error message)

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by NickDA225** [comment]
This error has begun to arise again today and I am completely unable to run my pipeline at all, again this is not dependent on accession as I am running two pipelines in parallel which are retrieving different sets of accessions, and both began to exhibit the error in the console simultaneously independent of the accession, but I can provide some accessions if you require. The error code this time is a little different:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x90ff55]

goroutine 1 [running]:
datasets_cli/v2/datasets.downloadData(0x0?, 0xaaaf86?, {0x0?, 0x0?}, {0xaaaf86?, 0x0?}, 0x0?)
	apps/public/Datasets/v2/datasets/datasets/Download.go:35 +0xb5
datasets_cli/v2/datasets.downloadDataForFile(0xc0000e7e88?, {0xb96060?, 0xc00030a240?}, {0xaaaf86, 0x10}, 0x0?)
	apps/public/Datasets/v2/datasets/datasets/Download.go:27 +0x18d
datasets_cli/v2/datasets.(*GeneProkDownloader).Download(0x0?)
	apps/public/Datasets/v2/datasets/datasets/GeneDownloader.go:283 +0xa5
datasets_cli/v2/datasets.createDownloadGeneAccession.func1(0xc00026e900?, {0xc000280610?, 0x1?, 0x1?})
	apps/public/Datasets/v2/datasets/datasets/DownloadGeneAccession.go:51 +0xee
github.com/spf13/cobra.(*Command).execute(0xc00026e900, {0xc0002805e0, 0x1, 0x1})
	external/com_github_spf13_cobra/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xfb5640)
	external/com_github_spf13_cobra/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	external/com_github_spf13_cobra/command.go:992
datasets_cli/v2/datasets.Execute()
	apps/public/Datasets/v2/datasets/datasets/root.go:494 +0x25
main.main()
	apps/public/Datasets/v2/cmd/datasets/main.go:10 +0x17
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x90ff55]

goroutine 1 [running]:
datasets_cli/v2/datasets.downloadData(0x0?, 0xaaaf86?, {0x0?, 0x0?}, {0xaaaf86?, 0x0?}, 0x0?)
	apps/public/Datasets/v2/datasets/datasets/Download.go:35 +0xb5
datasets_cli/v2/datasets.downloadDataForFile(0xc0000e7e88?, {0xb96060?, 0xc000312060?}, {0xaaaf86, 0x10}, 0x0?)
	apps/public/Datasets/v2/datasets/datasets/Download.go:27 +0x18d
datasets_cli/v2/datasets.(*GeneProkDownloader).Download(0x0?)
	apps/public/Datasets/v2/datasets/datasets/GeneDownloader.go:283 +0xa5
datasets_cli/v2/datasets.createDownloadGeneAccession.func1(0xc00026e900?, {0xc000280610?, 0x1?, 0x1?})
	apps/public/Datasets/v2/datasets/datasets/DownloadGeneAccession.go:51 +0xee
github.com/spf13/cobra.(*Command).execute(0xc00026e900, {0xc0002805e0, 0x1, 0x1})
	external/com_github_spf13_cobra/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xfb5640)
	external/com_github_spf13_cobra/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	external/com_github_spf13_cobra/command.go:992
datasets_cli/v2/datasets.Execute()
	apps/public/Datasets/v2/datasets/datasets/root.go:494 +0x25
main.main()
	apps/public/Datasets/v2/cmd/datasets/main.go:10 +0x17
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x90ff55]

goroutine 1 [running]:
datasets_cli/v2/datasets.downloadData(0x0?, 0xaaaf86?, {0x0?, 0x0?}, {0xaaaf86?, 0x0?}, 0x0?)
	apps/public/Datasets/v2/datasets/datasets/Download.go:35 +0xb5
datasets_cli/v2/datasets.downloadDataForFile(0xc000139ec8?, {0xb96060?, 0xc0003a2060?}, {0xaaaf86, 0x10}, 0x0?)
	apps/public/Datasets/v2/datasets/datasets/Download.go:27 +0x18d
datasets_cli/v2/datasets.(*GeneProkDownloader).Download(0x0?)
	apps/public/Datasets/v2/datasets/datasets/GeneDownloader.go:283 +0xa5
datasets_cli/v2/datasets.createDownloadGeneAccession.func1(0xc00026a900?, {0xc00027e5e0?, 0x1?, 0x1?})
	apps/public/Datasets/v2/datasets/datasets/DownloadGeneAccession.go:51 +0xee
github.com/spf13/cobra.(*Command).execute(0xc00026a900, {0xc00027e5b0, 0x1, 0x1})
	external/com_github_spf13_cobra/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xfb5640)
	external/com_github_spf13_cobra/command.go:1068 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	external/com_github_spf13_cobra/command.go:992
datasets_cli/v2/datasets.Execute()
	apps/public/Datasets/v2/datasets/datasets/root.go:494 +0x25
main.main()
	apps/public/Datasets/v2/cmd/datasets/main.go:10 +0x17
`

**Comment by ericcox1** [comment]
Hi @NickDA225,

Thanks for the update.

I have a few questions and requests for you.

1. Which version of the CLI are you using? If not the latest (15.13.1), please try running your pipeline again to see if the error has been fixed.
2. If that doesn't fix the issue, we ask that you try running the command with `--debug` and sharing the `Ncbi-Phid` value, which will allow us to collect some more information about what went wrong
3. Also, please share the exact command you are using and a few example accessions.
4. Have you tried running one pipeline at a time? Please give that a try and let us know how it goes.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by ericcox1** [comment]
I'm glad to hear it's working! 

>Perhaps the NCBI servers are throttling/blocking my download requests from time to time and this causes the issue?

This is a reasonable guess but NCBI Datasets has not implemented any throttling at this time (although that is something we are considering implementing in the future).
