### ISSUE TITLE
server sent GOAWAY and closed the connection

### ISSUE THREAD

**Issue by erinyoung** [ncbi/datasets#243]
I don't know if this is something you have any sway over, but it would be great if the server's timeout were extended.

I tried downloading genomes with datasets download (id_list.txt has 170 accession ids)

```
datasets download genome accession --inputfile id_list.txt --filename ncbi_dataset.zip
```

But this kept failing because of server timeout issues, so I tried dehydrate

```
datasets download genome accession --inputfile id_list.txt --dehydrated --filename ncbi_dataset.zip

unzip -o ncbi_dataset.zip -d ncbi_dataset

datasets rehydrate --directory ncbi_dataset
```

And I still get the same errors
```
Found 171 files for rehydration
Completed 162 of 171 [=============================================>--]  95%
http2: server sent GOAWAY and closed the connection; LastStreamID=71, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=71, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=71, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=71, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=71, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=71, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=71, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=71, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"
http2: server sent GOAWAY and closed the connection; LastStreamID=71, ErrCode=unknown error code 0xfffffc7a, debug="The user callback function failed"

Use datasets rehydrate <command> --help for detailed help about a command.
```

My googling suggests this is something server side, but I'd love to be wrong and get pointed in a good direction.

**Comment by syntheticgio** [comment]
Hi @erinyoung; we're tracking this internally; I don't have an update for you but wanted to let you know that it was seen!

Are you able to provide the IDs by chance?  And if you split into lets say two groups of IDs, do you have success then? Hopefully that could at least get you unblocked while we are investigating.

**Comment by erinyoung** [comment]
Here's a sample id list. This one has 218 samples, but I encountered the same error.

[id_list.txt](https://github.com/ncbi/datasets/files/11708457/id_list.txt)

**Comment by syntheticgio** [comment]
Hi @erinyoung .  I've tried to replicate but I can't seem to:
```
date; ./datasets version; time ./datasets download genome accession --inputfile id_list.txt --filename test.zip; date
Fri Jun  9 13:25:00 EDT 2023
datasets version: 15.3.1
Collecting 211  records [================================================] 100% 211/211
Downloading: test.zip    249MB done

real    0m18.906s
user    0m1.480s
sys     0m1.343s
Fri Jun  9 13:25:19 EDT 2023
```
This was also replicated on non-NIH servers without issue.

I noticed that there looks to be a blank line at the end of your id_list.txt.  This caused an issue on my end when I tried (different than yours though), but I'd be curious if you have better success when you remove it.  I'll note that down internally - ideally that wouldn't cause an issue and doesn't actually seem related to what you're reporting.

Can you share the version of datasets you are using (via `datasets version`)?

**Comment by erinyoung** [comment]
Thank you for looking into this! 

0m18.906s!

You have **much** faster download speeds than I do, so I imagine it would be difficult for you to recreate the error. 

I can replicate your command here at 970 kB/s outside of my employer's network.
```
$ date; datasets version; time datasets download genome accession --inputfile id_list.txt --filename test1.zip; date
Fri Jun  9 11:58:12 MDT 2023
datasets version: 15.3.1
Collecting 211  records [================================================] 100% 211/211
Downloading: test1.zip    249MB done

real	4m25.202s
user	0m4.339s
sys	0m2.680s
Fri Jun  9 12:02:38 MDT 2023
```

Sometimes, during high traffic times at where I work, my download speeds are much lower (~50-100 kB/s), and that is when I run into issues. The "GOAWAY" issue appears to happen when the command takes more than 19 minutes.

id_list.txt doesn't have a space at the end of the file on my end. Perhaps github adjusts files when they are uploaded. My apologies.

**Comment by syntheticgio** [comment]
Thanks for the additional information!  Its possible I introduced the extra newline too; but glad to see we can remove that.  I'll update our internal ticket with this additional information so we can look into it at that level.  I'll post once I know something.

**Comment by olearyna** [comment]
Hi @erinyoung 

Thanks for reporting this issue and sorry you are experiencing slow download speeds using NCBI Datasets. We looked into the issue and we don't have an immediate solution for users experiencing slow download speeds but we're exploring options to improve this in future updates. We'll keep you informed as we develop. 

Nuala 

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS [Contractor]
Bethesda, MD 20892
