### ISSUE TITLE
Taxa out of scope

### ISSUE THREAD

**Issue by jodyphelan** [ncbi/datasets#246]
I'm trying to download all complete dengue genomes using the ncbi taxonomy id [12637](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=12637&lvl=3&lin=f&keep=1&srchmode=1&unlock). This command worked a few days ago but doens't anymore:

```
datasets download virus genome taxon 12637 --complete-only
```

It fails with this error now:

```
The download virus genome taxon command only supports virus taxa.
For data on other organisms, please use the download genome taxon command.

Error: taxa 12637 is out of scope
```

**Comment by ericcox1** [comment]
Hi Jody,

The outage has been resolved and the command in your original post should now work as expected.

Feel free to open a new issue if you see any other problems.

Best,
Eric

**Comment by corneliusroemer** [comment]
Thank you for the quick fix!
