### ISSUE TITLE
Unable to download by gene symbol

### ISSUE THREAD

**Issue by dwwaite** [ncbi/datasets#251]
Hi,

I'm trying to download a set of nad5 genes (NADH dehydrogenase subunit 5) but when I run the command

```bash
datasets download gene symbol nad5
```

I just receive the feedback `Error: No genes found that match selection`. If I instead search by a known instance of this gene in *Arabidopsis*:

```bash
datasets summary gene gene-id 36335705
```

I get the JSON feedback, which clearly includes the content:

```json
"common_name":"thale cress",
"description":"NADH dehydrogenase subunit 5",
"gene_id":"36335705",
"orientation":"plus",
"protein_count":1,
"symbol":"nad5",
"tax_id":"3702",
"taxname":"Arabidopsis thaliana",
"type":"PROTEIN_CODING"
```

So it appears that datasets is aware of the nad5 symbol. Also, running a test on a different gene (e.g. `datasets download gene symbol ACRV1`) works fine.

Any help would be greatly appreciated.

Cheers,
Dave

**Comment by ericcox1** [comment]
Hi Dave,

Thanks for opening this issue. 

When querying by gene symbol, you'll need to specify the taxon if it's anything other than human. 

For example, to query for the _Arabidopsis thaliana_ nad5 gene, use:

`datasets download gene symbol nad5 --taxon 'arabidopsis thaliana'`

I hope that helps. Let me know if you have any other questions. You can find more information about how to query for gene data in our how-to guide on how to [download a gene data package](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genes/download-gene-data-package/).

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by dwwaite** [comment]
Thanks for your quick response. It appears that this only works at the species level, and you cannot use a higher taxonomic rank to get results from a group of organisms (for example, all NAD5 genes in a particular plant family). Is there a way to download for a higher grouping, or should I just write a loop to download over all the species of interest?

**Comment by ericcox1** [comment]
Hi @dwwaite,

>It appears that this only works at the species level, and you cannot use a higher taxonomic rank to get results from a group of organisms

You are correct. The ability to query by a gene symbol and a higher taxonomic rank is a feature we would like to add in the long term.
>should I just write a loop to download over all the species of interest

Yes, I think using a loop is the right way to do this.

Here's an example that only queries for species in the _Brassicaceae_ family with an annotated RefSeq assembly:
```
datasets summary genome taxon brassicaceae --assembly-source RefSeq --as-json-lines | \
dataformat tsv genome --fields organism-tax-id --elide-header | \
while read TAX_IDS; do \
datasets summary gene symbol nad5 --taxon $TAX_IDS --as-json-lines | \
dataformat tsv gene --fields symbol,gene-id,tax-id,tax-name --elide-header | \
column -t -s$'\t'; \
done
nad5  36335705  3702  Arabidopsis thaliana
nad5  4237891  3708  Brassica napus
nad5  56140990  3711  Brassica rapa
nad5  40490657  81985  Capsella rubella
nad5  13630175  3726  Raphanus sativus
```

Best,
Eric
