### ISSUE TITLE
Feature request - Filter BioProject by taxon

### ISSUE THREAD

**Issue by muffato** [ncbi/datasets#252]
Hello,

Currently, `datasets summary genome` has two modes: `accession`, which I can use to get genomes for a certain BioProject, and `taxon` to search by taxon.
I'd like to be able to combine both search filters: get all genomes for a certain BioProject and a certain clade.

Is it possible with the current CLI ? If not, is it something you could look into ?

Best regards,
Matthieu

**Comment by ericcox1** [comment]
Hi Matthieu,

Thanks for opening this issue.

I think the best way to do this is to first query by taxon and then use grep to pull out genomes associated with a particular BioProject, like this:
```
# Get all waterfowl GenBank genomes, then grep for VGP genomes
datasets summary genome taxon anatidae --as-json-lines --assembly-source genbank | \
dataformat tsv genome --fields accession,assminfo-bioproject-lineage-accession | \
grep PRJNA489243
GCA_015476345.1	PRJNA489243
GCA_009819795.1	PRJNA489243
GCA_009819845.1	PRJNA489243
GCA_009769485.2	PRJNA489243
GCA_009769625.2	PRJNA489243
```

Please let me know if you have any other questions.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by muffato** [comment]
Hi Eric,

Thank you very much for your answer. That should make the trick.

Also, you made me discover the `--as-json-lines` option and the `dataformat` tool. I was processing the output as a single JSON, and had a `jq` script to extract some fields into a TSV. `dataformat` does that very well too !

One thing that bit me is that `assminfo-bioproject-lineage-accession` causes `dataformat` to print the same assembly multiple times if there are multiple associated BioProjects. Initially I couldn't make sense of the number of results. Maybe that's something that could be added to the documentation ?

Best wishes,
Matthieu
