### ISSUE TITLE
Large dataset download.

### ISSUE THREAD

**Issue by elormakresi** [ncbi/datasets#253]
Here is my error: (ncbi_datasets) [jakresi@login1.swan c_perf_reference_genomes]$ datasets download genome taxon 1502 --dehydrated --filename c_perf_ref_genomes.zip
Collecting 2,180  records [================================================] 100% 2180/2180
Downloading: c_perf_ref_genomes.zip    388kB 14kB/s
Error: Internal error (invalid zip archive). Please try again

I tried using "Clostridium perfringens" as well.

**Comment by mtntsuchiya** [comment]
Hi elormakresi,
Thank you for letting us know of this issue.

Unfortunately, I was not able to reproduce it. Would you mind trying it again, and this time including the flag `--debug` and share the output with us, in case it fails again? 

When I attempt the download using your command, the compressed file was 844KB. 

Thank you so much, and I look forward to hearing back from you.

Best,
Mirian

Mirian T. N. Tsuchiya, Ph.D.
Bioinformatics Data Wrangler (contractor)
NCBI Datasets (NCBI/NLM/NIH)
(she/her/hers)
