### ISSUE TITLE
Error: [gateway] Internal Server Error when downloading orthologs of specific taxonomic range

### ISSUE THREAD

**Issue by BELKHIR** [ncbi/datasets#254]
Hi,
I got this error when I try to download orthologs for a taxonomic group.
Ex:
$ datasets download gene gene-id 59272 --ortholog mammals

However, when using --ortholgs all  I can download  the Gene Ortholog Data Package without any problem.

Any advice ?

I am using datasets version: 15.11.0

Regards,

**Comment by mtntsuchiya** [comment]
Hi Belkhir,
Thank you so much for letting us know of this issue. 

I was able to replicate the same issue and our developers will look into it. We'll post any updated regarding it in this thread. 

Thanks again.
Best,
Mirian

Mirian T. N. Tsuchiya, Ph.D.
Bioinformatics Data Wrangler (contractor)
NCBI Datasets (NCBI/NLM/NIH)
(she/her/hers)

**Comment by ericcox1** [comment]
Hi Belkhir,

This bug has been fixed in the latest version of the NCBI Datasets command line tools, [v15.13.0.](https://github.com/ncbi/datasets/releases/tag/v15.13.0)

Here's a snippet of output when running the original command you shared above:
```
datasets download gene gene-id 59272 --ortholog mammals --filename ace2.zip
Collecting 205  records [================================================] 100% 205/205
Collecting 205  records [================================================] 100% 205/205
Downloading: ace2.zip    508kB done

unzip -cq ace2.zip ncbi_dataset/data/data_report.jsonl | dataformat tsv gene --fields symbol,common-name | head -5
Symbol	Common Name
ACE2	pig
Ace2	domestic guinea pig
ACE2	olive baboon
Ace2	degu
```

Best,
Eric
