### ISSUE TITLE
Containers for NCBI datasets

### ISSUE THREAD

**Issue by priyanka-surana** [ncbi/datasets#256]
Do you release docker containers for ncbi datasets? If not, would you consider setting it up. For example, Bioconda releases automatically get docker and singularity containers.

**Comment by ericcox1** [comment]
Hi @priyanka-surana,

Thanks for opening this issue. 

Unfortunately, we currently don't have plans to release docker containers for NCBI Datasets software. We may revisit this in the future.

Best,
Eric
