### ISSUE TITLE
Four example NCBI datasets jupyter notebooks failed to load

### ISSUE THREAD

**Issue by DavidWilliamRoberts** [ncbi/datasets#257]
The example and excellent jupyter notebooks failed to load.
Below is copy of the returned error notice for each link.
Please help

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Look at examples in our jupyter notebooks:
https://www.ncbi.nlm.nih.gov/datasets/docs/v1/languages/python/
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Browse and download [genomes].

[genomes] - Returned:
https://mybinder.org/v2/gh/ncbi/datasets/master?filepath=examples/jupyter/ncbi-datasets-pylib/ncbi-datasets-assembly.ipynb

Build logs
 ---> Running in 9378f04589e5
Removing intermediate container 9378f04589e5
 ---> 53b2dc90ed23
Step 43/47 : ENV PYTHONUNBUFFERED=1
 ---> Running in 3fbe20944299
Removing intermediate container 3fbe20944299
 ---> ec8a82ae04bd
Step 44/47 : COPY /python3-login /usr/local/bin/python3-login
 ---> cababab55d85
Step 45/47 : COPY /repo2docker-entrypoint /usr/local/bin/repo2docker-entrypoint
 ---> 0ae3ca48fd3c
Step 46/47 : ENTRYPOINT ["/usr/local/bin/repo2docker-entrypoint"]
 ---> Running in dffe868527e4
Removing intermediate container dffe868527e4
 ---> 6b381eaa8880
Step 47/47 : CMD ["jupyter", "notebook", "--ip", "0.0.0.0"]
 ---> Running in 98fc6954c3d4
Removing intermediate container 98fc6954c3d4
 ---> 0a97ccac7bcf
{"aux": {"ID": "sha256:0a97ccac7bcf9971934896a0badb0b24c18f0e272c68befae4c8ba77084ebf69"}}Successfully built 0a97ccac7bcf
Successfully tagged gesiscss/binder-r2d-g5b5b759-ncbi-2ddatasets-5591bc:b2fb6042d1880ae8ba4daa274927d8bab8215da7
Error during build: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Browse and download [genes] and [analyze gff3 files].

[genes] - Returned:
https://hub.ovh2.mybinder.org/user/ncbi-datasets-ak00pnuz/tree/examples/jupyter/ncbi-datasets-pylib/ncbi-datasets-gene.ipynb

404 : Not Found
You are requesting a page that does not exist!

[analyze gff3 files] - Returned:
https://mybinder.org/v2/gh/ncbi/datasets/master?filepath=examples/jupyter/ncbi-datasets-pylib/ncbi-datasets-gff3.ipynb

Build logs
Waiting for build to start...
failed to create fsnotify watcher: too many open files
~~~~~~~~~~~~~~~~~~~~~

Browse and download [SARS-CoV-2 assemblies].

Returned:
https://mybinder.org/v2/gh/ncbi/datasets/master?filepath=examples/jupyter/ncbi-datasets-pylib/ncbi-datasets-virus.ipynb

Build logs
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2dockerqb9ta382'...
failed to create fsnotify watcher: too many open files

**Comment by ericcox1** [comment]
Hi @DavidWilliamRoberts, 

Thanks for opening this issue. 

The broken binder links are outdated, and while we removed other instances of the links on our pages, we must have missed the ones you found on the [v1 python documentation page](https://www.ncbi.nlm.nih.gov/datasets/docs/v1/languages/python/). We will remove them sometime in the next week or so.

For your information, our python library development has been paused and does not support the latest version of the API, v2. As a result, we recommend that you try using the NCBI Datasets [command-line tools](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/download-and-install/) instead, which feature error handling and retries. If you're interested in exploring the command-line tools using a jupyter notebook, you may be interested in trying this updated notebook: [Getting started with NCBI Datasets v14](https://github.com/ncbi/datasets/blob/master/training/2023-01-03-datasets-cli14/2023-01-03-datasets-v14_with-outputs.ipynb). We don't have a binder link available for this notebook but please feel free to download it and run in your own jupyter environment.

I hope that helps. Thanks again for your feedback.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by ericcox1** [comment]
We have removed the broken binder links.

-Eric
