### ISSUE TITLE
Error rename  [windows]

### ISSUE THREAD

**Issue by sbridel** [ncbi/datasets#259]
![img](https://github.com/ncbi/datasets/assets/7995272/d7c3f6d8-a601-468a-b0e0-8d9cd064c44d)

HI, I have this error of rename on several pcs where I work. I dont know if it's a config like firewell/vpn problem or a problem within the script...

Tested with both version  13.43.2 and 15.13.1

**Comment by ericcox1** [comment]
Hi @sbridel,

Thanks for opening this issue. I discussed this with the development team and we think that there are likely some temporary files that could be causing the issue. Please delete all the files in the directory that is being rehydrated and try the download again.

Best,
Eric
