### ISSUE TITLE
[feature request] Add `--assembly-version` option for virus downloads

### ISSUE THREAD

**Issue by kapsakcj** [ncbi/datasets#261]
Hi,

It seems like the option `--assembly-version <ver>` is available for the command:
```bash
# works
datasets download genome accession --assembly-version <ver>
```
but is not available for genomes pulled from NCBI virus:
```bash
# throws an error
$ datasets download virus genome accession --assembly-version <ver>
Error: unknown flag: --assembly-version

Use datasets download virus genome accession <command> --help for detailed help about a command.
```
could that be added in the future?

I'm currently using `datasets` v15.11.0. Apologies if this has already been implemented, I didn't see anything in the release notes about this.

I'm slowly discovering the differences between these 2 sub-commands 😄 
```
datasets download genome accession
datasets download virus genome accession
```

**Comment by ericcox1** [comment]
Hi @kapsakcj,

Thanks again for opening this issue and I appreciate you moving it to a _new_ issue.

Would you mind sharing a little bit more information about you are trying to do and how this feature would help? I'm guessing that you are trying to specifically download _only_ the latest viral genomes for a particular taxon. Is that correct? If that's the case, do you mind sharing a few example accessions of _non-latest_ records that are returned using your query?

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by kapsakcj** [comment]
Hi Eric,

> _I'm guessing that you are trying to specifically download only the latest viral genomes for a particular taxon. Is that correct?_

That is correct, I want to ensure that I'm only downloading the latest versions of viral genomes (particularly sars-cov-2). Is that the default behavior? (apologies if this is in the documentation, I couldn't tell from the `--help` output)

I have not encountered accessions where I have downloaded the non-latest versions using my query. I will share any if I come across them though.

----

For some more context: I have a workflow for running `datasets` and was under the naive assumption that the two commands below have the same options available to both:
```
datasets download genome accession
datasets download virus genome accession
```

Another difference I noticed is the output directory structure & naming conventions differ between the two:

The unzipped output of the command `datasets download genome accession GCF_008807055` is structured like so,
```
ncbi_dataset/
└── data
    ├── GCF_008807055.1
    │   └── GCF_008807055.1_ASM880705v1_genomic.fna
    ├── assembly_data_report.jsonl
    └── dataset_catalog.json
```
And the unzipped output of the command `datasets download virus genome accession OR465450.1` is structured slightly differently with different filenames
```
ncbi_dataset/
└── data
    ├── data_report.jsonl
    ├── dataset_catalog.json
    ├── genomic.fna
    └── virus_dataset.md
```

Due to these differences I'm required to duplicate my workflow code & maintain separate versions for calling each of the sub-commands.

It is HUGE request to make everything identical between the two, so please don't let this particular request snowball, but might be something to consider long-term.

The authors of `samtools` have tirelessly dealt with this sort of thing over many years and not everything is equivalent between the various samtools subcommands, options, and output files.

It's a very difficult problem to tackle 😅

**Comment by ericcox1** [comment]
Hi Curtis,

Thanks for the information. 

>I want to ensure that I'm only downloading the latest versions of viral genomes (particularly sars-cov-2). Is that the default behavior? (apologies if this is in the documentation, I couldn't tell from the --help output)

Yes, this is the default behavior, but it is not documented. 

>Another difference I noticed is the output directory structure & naming conventions differ between the two

As you point out, there are differences in directory structure and file names between what we call the [genome data package](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/data-packages/genome/) compared to the [virus data package](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/data-packages/virus-genome/).

The reason that we created a separate, specialized virus data package is because there is a different set of metadata fields available for virus genomes and most of the virus genome data comes from a different database at NCBI. In general, we would recommend using `datasets download virus genome accession` _instead of_ `datasets download genome accession` for retrieving virus genome data, although you may have good reason for using both commands to be more comprehensive. I'm curious, is there information about virus genomes that you are getting from `datasets download genome accession` that is not available from `datasets download virus genome accession`? We may have a more productive conversation on zoom if you're interested. I'm happy to set something up with a few members of the team sometime this week or next. Please let me know.

Best,
Eric

**Comment by kapsakcj** [comment]
Hi Eric,

I appreciate the explanation and links to the documentation on the data packages, that helps explain the differences. Thank you.

> _I'm curious, is there information about virus genomes that you are getting from `datasets download genome accession` that is not available from `datasets download virus genome accession`?_

With the accessions I was testing with (sars-cov-2 accessions) it seemed that only `datasets download virus genome accession` would run successfully whereas `datasets download genome accession` threw an error. It was not a difference in the info or files downloaded.

Appreciate the offer to meet, but I don't think that is necessary at this time.

Thank you!

**Comment by kapsakcj** [comment]
Sure thing, my apologies! I thought it was in my original post.

The one I was testing with was this `OR461132.1` which is a recently submitted/published sars-cov-2 genome

Using `datasets` v 15.11.0:
```
$ datasets download genome accession OR461132.1
Error: invalid or unsupported assembly accession: OR461132.1

Use datasets download genome accession <command> --help for detailed help about a command.

$ datasets download virus genome accession OR461132.1
New version of client (15.16.0) available at https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets
Downloading: ncbi_dataset.zip    14.6kB done
```

**Comment by kapsakcj** [comment]
Here's another sars-cov-2 accessions that exhibits the same behavior: `OR177999.1`. This one is relatively recent too, released in late june 2023

**Comment by ericcox1** [comment]
Hi @kapsakcj,

Sorry for the delay. For your purposes, you should be able to get all the data that you need using `datasets download virus genome accession`.

>With the accessions I was testing with (sars-cov-2 accessions) it seemed that only datasets download virus genome accession would run successfully whereas datasets download genome accession threw an error. 

>The one I was testing with was this OR461132.1 which is a recently submitted/published sars-cov-2 genome

`datasets download genome accession` accepts assembly accessions and BioProject accessions, for example, `GCF_000001405.40` or `PRJNA289059`.  Only a small subset of virus genomes have been assigned assembly accessions.

In contrast, `datasets download virus genome accession` accepts nucleotide accessions, for example, `OR461132.1`, which have been assigned to all virus genomes.

-Eric

**Comment by kapsakcj** [comment]
Thank you, Eric. Appreciate the help and information!
