### ISSUE TITLE
Input gene symbols are not returned in final table, request to add "input" field to dataformat

### ISSUE THREAD

**Issue by ksegaba** [ncbi/datasets#262]
Hello, I have a list of gene IDs that I want to get the gene metadata for. However, I can't map the results of the table if the initial input IDs are not include in the final table.

This is the command I ran:
./datasets summary gene accession --inputfile tblastx_genes_for_ncbi.txt --as-json-lines | ./dataformat tsv gene

It returned all the search fields for each accession in tblastx_genes_for_ncbi.txt, except for the accessions themselves. 

This is a snippet of what tblastx_genes_for_ncbi.txt looks like: (I want these in the final table)
X68321.1
X68321.1
X13736.1
X56933.1
X56933.1
X05218.1
NM_176613.2
X05605.1
X05605.1
NM_176670.2
X56685.1
X15112.1
X13617.1
X13617.1
X59693.1
X59693.1

I appreciate any guidance, thank you.

**Comment by ericcox1** [comment]
Hi @ksegaba,

Thanks for opening this issue. 

We have had some other users ask for this feature and we are working on it. I'll comment on this thread when it's ready.

Note that [datasets summary gene accession](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/command-line/datasets/summary/gene/datasets_summary_gene_accession/) recognizes RefSeq nucleotide and protein accessions (e.g., NM_176613.2 and NM_176670.2), but not GenBank accessions (e.g., X68321.1, X13736.1, and the other accessions in your list).

In the meantime, you could try the following alternative approaches to get the initial input IDs mapped to the gene metadata:
1. Use `datasets` without `dataformat` and get the metadata in JSON format
2. Join the query/input ID to the metadata table in three steps, using the third-party tool [jq](https://jqlang.github.io/jq/)

### Use `datasets` without `dataformat` and get the metadata in JSON format
Note that the input ID is shown in the `query` field.
```
datasets summary gene accession NM_176613.2
{"reports": [{"gene":{"annotations":[{"annotation_name":"NCBI eukaryotic genome annotation pipeline","annotation_release_date":"2021-05-24","assembly_accession":"GCF_002263795.2","assembly_name":"ARS-UCD1.3","genomic_locations":[{"genomic_accession_version":"NC_037332.1","genomic_range":{"begin":"26369899","end":"26378378","orientation":"plus"},"sequence_name":"5"}]}],"chromosomes":["5"],"common_name":"cattle","description":"ATP synthase membrane subunit c locus 2","gene_groups":[{"id":"517","method":"NCBI Ortholog"}],"gene_id":"337887","nomenclature_authority":{"authority":"VGNC","identifier":"VGNC:55848"},"orientation":"plus","protein_count":3,"swiss_prot_accessions":["P07926"],"symbol":"ATP5MC2","synonyms":["ATP5G2"],"tax_id":"9913","taxname":"Bos taurus","transcript_count":3,"transcript_type_counts":[{"count":1,"type":"PROTEIN_CODING"},{"count":2,"type":"PROTEIN_CODING_MODEL"}],"type":"PROTEIN_CODING"},"query":["NM_176613.2"]}],"total_count": 1}
```
### Join the query/input ID to the metadata table
1. Create a two-column table with the Gene ID and input ID
`datasets summary gene accession NM_176613.2 NM_176670.2 | jq -r '.reports[] | [.query,.gene.gene_id] | flatten | @tsv' > query.tsv`
2. Create a metadata table 
`datasets summary gene accession NM_176613.2 NM_176670.2 --as-json-lines | dataformat tsv gene --elide-header > metadata.tsv`
3. Join the two tables. Note that the Gene ID is in the first column and the input ID is in the last column, with the rest of the metadata in the intervening columns.
```
join metadata.tsv query.tsv -1 19 -2 2 -t$'\t'
337887	GCF_002263795.2	ARS-UCD1.3	NC_037332.1						plus	26369899	26378378	5	2021-05-24	NCBI eukaryotic genome annotation pipeline	5	cattle	ATP synthase membrane subunit c locus 2		PROTEIN_CODING							517	NCBI Ortholog	VGNC	VGNC:55848		plus	3							P07926	ATP5MC2	ATP5G2	9913	Bos taurus	3	NM_176613.2
338081	GCF_002263795.2	ARS-UCD1.3	NC_037334.1						plus	43683704	43685876	7	2021-05-24	NCBI eukaryotic genome annotation pipeline	7	cattle	ATP synthase F1 subunit delta		PROTEIN_CODING							513	NCBI Ortholog	VGNC	VGNC:26302		plus	1									P05630	ATP5F1D	ATP5D	9913	Bos taurus	1	NM_176670.2
```

I hope that helps.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
