### ISSUE TITLE
Query string 'filters.assembly_version'

### ISSUE THREAD

**Issue by alvanuffelen** [ncbi/datasets#268]
I read in the [API ](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/rest-api/#get-/genome/taxon/-taxons-/dataset_report) docs that `assembly_version` can be controlled with `filters.assembly_version`.
> Return all assemblies, including replaced and suppressed, or only current assemblies

However, using follow API call:
https://api.ncbi.nlm.nih.gov/datasets/v2alpha/genome/taxon/4930/dataset_report?filters.reference_only=false&filters.exclude_paired_reports=true&filters.exclude_atypical=true&filters.assembly_version=current&page_size=1000

returns a suppressed assembly `GCF_000292725.1` (line 697)
Shouldn't only `current` assemblies be returned? Or does `current` rather mean `latest` (https://github.com/ncbi/datasets/issues/216#issuecomment-1464062239)?

**Comment by ericcox1** [comment]
Hi @alvanuffelen,

Thanks for opening this issue. 

>However, using follow API call:
https://api.ncbi.nlm.nih.gov/datasets/v2alpha/genome/taxon/4930/dataset_report?filters.reference_only=false&filters.exclude_paired_reports=true&filters.exclude_atypical=true&filters.assembly_version=current&page_size=1000
returns a suppressed assembly GCF_000292725.1 (line 697)

>Or does current rather mean latest

This is the intended behavior and the answer to your question is yes. I also acknowledge that this is a little bit unexpected. Let me review this with the team and I'll try to get back to you soon.

Best,
Eric

**Comment by ericcox1** [comment]
Thanks @alvanuffelen, we're going to update the API so that it does _not_ return suppressed assemblies when querying by a TaxID. I'll update this thread when the change is in production.

-Eric
