### ISSUE TITLE
Virus download issues

### ISSUE THREAD

**Issue by fienx** [ncbi/datasets#270]
Hi, I am trying to download some virus data and am getting a "Error: No valid accessions were passed" message. I have been able to download non-viral datasets just fine, so I looked at the documentation for viruses before downloading and adjusted what I needed to do. My command line prompt was this:
`datasets download virus genome accession NC_001664.4 --filename data/genomes/virus/NC_001664.4/NC_001664.4.zip`
Which as far as I can tell is correct. I have tried many different viral accessions too, all with the same message.
What am I doing wrong? I also tried without the version number "NC_001664" but same error too.
I even tried the example provided
`datasets download virus genome accession NC_045512.2 --include genome,cds,protein`
and still same issue.

I am running version 15.13.1
EDIT: updated to 15.21.0 and still same issue.

**Comment by syntheticgio** [comment]
Hi @fienx .  I'm not able to replicate the problem this morning.  I believe there were some network related issues last night, would you be able to try again and see if you get the same error?

**Comment by fienx** [comment]
Thanks for responding,

Yes, it is working now. Must have been the network related issues causing the problem.

Thanks again.
