### ISSUE TITLE
Gogvych

### ISSUE THREAD

**Issue by Gogvych** [ncbi/datasets#272]
Does this snippet of code belong to Python 3:

datasets download genome taxon human --reference --filename human-reference.zip

**Comment by olearyna** [comment]
Hi Gogvych,

Thank you for contacting us. The snippet you've shared is an example of a download request utilizing the NCBI Datasets command line tool. You might want to consider using the command line tool. You can find documentation on downloading the tool [here](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/download-and-install/). Additionally, we have 'how-to' guides available for initiating genome downloads on the CLI [here](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/download-genome/). The tool is also available as a conda package at https://anaconda.org/conda-forge/ncbi-datasets-cli.

If you could provide more details on your task, we would be glad to assist you further.

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS
