### ISSUE TITLE
`dataformat tsv genome --inputfile metadata.jsonl` can't convert `.jsonl` get from `datasets summary genome accession`

### ISSUE THREAD

**Issue by NickShanyt** [ncbi/datasets#276]
Hi,
I want to retrieve some metadata from a specified GCFids file, and I can do this using :
`
for i in 'cat GCF_ID.txt';  do datasets summary genome accession "$i" >>GCF_id_metadata_new.jsonl; done
`
#here use ' to present `

This worked, and I got the `GCF_id_metadata_new.jsonl` file with each line representing a record in the following approximate format:
`{"reports": [{"accession":"GCF_000002945.1",……}],"total_count": 1}`

Then I want to covert this .json to .tsv, I used 
`dataformat tsv genome --inputfile GCF_id_metadata_test.jsonl` 
It doesn't work , and it reports:

> **dataformat doesn't recognize this input**
> **Error:  unknown field "reports"**

I'm not sure what went wrong. What should I do in order to achieve my goal?

**Comment by NickShanyt** [comment]
Ah, after I raised the issue, I went through the closed issue and tried to add --as-json-lines to the command to get the metadata, and then I got a .jsonl that was truly "one row per record", and it worked.

This problem has been solved.

**Comment by ericcox1** [comment]
Hi @NickShanyt,

Thanks for opening this issue. I'm glad you were able to find a solution.

Alternatively, you can use `--inputfile` and pipe the output of _datasets_ directly to _dataformat_ as follows:

```
datasets summary genome accession --inputfile GCF_ID.txt --as-json-lines | \
dataformat tsv genome
```

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
