### ISSUE TITLE
How to download paired gene mRNA-CDS-protein sequence information?

### ISSUE THREAD

**Issue by ZYZhang17** [ncbi/datasets#278]
Hello,
I've been trying to download human gene mRNA sequence information(each gene containing a mRNA sequence and its corresponding CDS, UTR, protein seq) using the following command in shell:
```shell
datasets download gene taxon human --include gene,rna,protein,cds,5p-utr,3p-utr --filename human-mRNA.zip
```
However, it seems that the downloaded mRNA CDS sequences and mRNA protein sequences do not correspond one-to-one. In other words, there are slight differences between many mRNA CDS sequences that encode protein sequences and the corresponding protein sequences provided in the FASTA file. Moreover, the order of the two FASTA files is not completely paired, with some missing sequences in between. 
How can I solve this problem?

**Comment by ericcox1** [comment]
Hi @ZYZhang17,

Thanks for opening this issue.

> there are slight differences between many mRNA CDS sequences that encode protein sequences and the corresponding protein sequences provided in the FASTA file.

This is expected.
While the CDS sequences generally match the genome, mRNA and protein sequences may differ from the genome (and the CDS sequences) if there is reason to believe the genome sequence is in error or the genome sequence represents a known mutation. In such cases, the RefSeq mRNA and protein sequences may be based on  transcript data or other data available in public archives.

I hope that helps.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
