### ISSUE TITLE
Issue with `summary genome taxon` and a taxon name.

### ISSUE THREAD

**Issue by muffato** [ncbi/datasets#280]
Hello,

I'm seeing a weird behaviour for the `datasets summary genome taxon` command. It was fine Friday Oct 27th 1am BST, but not Sat Oct 28th 1am BST (and still broken today).

It seems that the taxon name resolution stopped working. See this example for Eutheria ([taxon ID 9347](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=9347&lvl=3&p=has_linkout&p=blast_url&p=genome_blast&lin=f&keep=1&srchmode=1&unlock))
```console
$ datasets summary genome taxon 9347 --as-json-lines | dataformat tsv genome --fields organism-name,assminfo-name,accession,assminfo-submitter --elide-header | wc -l
2760
$ datasets summary genome taxon Eutheria --as-json-lines | dataformat tsv genome --fields organism-name,assminfo-name,accession,assminfo-submitter --elide-header | wc
1
$ datasets version
datasets version: 15.25.0
$ dataformat version
15.25.0
```

What's especially worrying is that the one assembly returned above is _not_ a mammal: it's the tobacco thrip !
```
Frankliniella fusca     ASM2937930v1    GCA_029379305.1 University of Georgia
```

Querying for _Mammalia_ returns 12 _viruses_, for example this one:
```
Mammalian orthoreovirus ASM3152850v1    GCA_031528505.1 Tree Shrews Germplasm Resources Centre, Institute of Medical Biology, CAMS, Peking Union Medical College
```
and not even the trip from above, even though _Mammalia_ is above _Eutheria_.

I checked _Lepidoptera_ as well and also got viruses.

Best regards,
Matthieu

**Comment by syntheticgio** [comment]
Hi Matthieu,

We're taking a look at this internally - I don't have any updates at the moment but wanted to let you know.

John

**Comment by ericcox1** [comment]
Hi @muffato,

Thanks for opening this issue. This bug has been fixed.

The genome counts now match when using the Tax ID or the taxonomic name for Eutheria:
```
datasets summary genome taxon 9347 --as-json-lines | dataformat tsv genome --fields organism-name,assminfo-name,accession,assminfo-submitter --elide-header | wc -l
2760

datasets summary genome taxon Eutheria --as-json-lines | dataformat tsv genome --fields organism-name,assminfo-name,accession,assminfo-submitter --elide-header | wc -l
2760
```
I also checked _Mammalia_ and _Lepidoptera_ and I couldn't find any viruses 😄 

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by muffato** [comment]
All good. Thank you very much @ericcox1 !
