### ISSUE TITLE
Error: [gateway] Gateway Error (429 Too Many Requests)

### ISSUE THREAD

**Issue by hunglin59638** [ncbi/datasets#284]
I encountered an error while using the following command:

```
datasets download virus genome accession NC_063383.1
```
Error Message
```
Error: [gateway] Gateway Error (429 Too Many Requests)
```

**Comment by ericcox1** [comment]
Hi @hunglin59638,

Thanks for opening this issue. We received an unusually large volume of requests for virus genome data that have caused this error.

This issue is now resolved.

Best,
Eric

**Comment by annotatebio** [comment]
Hi,

Unfortunately, I am facing the same error now - trying to download annotation data in batches of 50 genomes and I'm getting a following error:

```bash
PROCESSING CHUNK 0 (RECORDS 0 - 50)
New version of client (16.19.0) available at https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets.
Collecting 50 genome records [================================================] 100% 50/50
Error: [gateway] Gateway Error (429 Too Many Requests)
```

Would this be due to older version of the client? Would updating potentialy solve this issue, or is there something else I can do?

**Comment by ericcox1** [comment]
Hi @annotatebio,

Thanks for your report. We received an unusually large volume of requests for genome data that have caused this error.

This issue is now resolved.

Best,
Eric
