### ISSUE TITLE
Downloading all species datasets (assembly in FASTA and annotation in GFF format) for research project

### ISSUE THREAD

**Issue by recervictory** [ncbi/datasets#285]
I am currently working on a research project that requires me to download **all species datasets** (assembly in `FASTA` and annotation in `GFF` format) for a specific group of organisms. I have tried using the NCBI FTP site and the NCBI Datasets Genome Data Package, but I am having trouble finding all of the datasets that I need.

I would appreciate any suggestions on how to download all of the species datasets that I need. In particular, I am interested in the following:

- What is the best way to download all of the species datasets in a single batch?
- Are there any specific tools or resources that I can use to download the datasets?
- Are there any specific challenges or pitfalls that I should be aware of when downloading the datasets?

I would also be grateful if anyone could provide me with links to any specific resources or documentation that would be helpful for downloading the datasets.

Thank you for your time and assistance.

**Comment by ericcox1** [comment]
Hi @recervictory,

Thanks for opening this issue. 

I recommend trying the NCBI Datasets [command-line tools](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/download-and-install/). You can use the _datasets_ command-line tool to download genomic `FASTA` sequences for all assembled genomes, while annotation in `GFF` format is available for annotated genomes.
For more information, see the [Download a genome data package](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/download-genome/) How-To guide.
>I have tried using the NCBI FTP site and the NCBI Datasets Genome Data Package, but I am having trouble finding all of the datasets that I need.

Could you please be more specific about which data you are having trouble finding? If you could provide any accessions or other identifiers that would be helpful.

I look forward to hearing from you soon.

Best,
Eric

**Comment by recervictory** [comment]
Dear Eric, @ericcox1,

Thank you for your prompt response. I appreciate your recommendation to use the NCBI Datasets command-line tools. 

I have reviewed the Download a genome data package How-To guide, but I am still having trouble finding all of the commands that I need. I am specifically interested in downloading all species genomes with complete sequences with their meta data, Fasta sequence and annotation in GFF format. Is there a specific command that I can use to do this?

In addition to my question about the command-line tools, I would also like to connect with you on LinkedIn. I think it would be great to stay in touch and learn updates on the NCBI Datasets project. Please let me know if you are interested in connecting.

Thank you for your time and assistance.

Sincerely,
Victor Banerjee


CSIR - Centre for Cellular and Molecular Biology
Hyderabad, India
recervictory@gmail.com
https://www.linkedin.com/in/victorbanerjee/

**Comment by ericcox1** [comment]
Hi @recervictory,

Here is an example command for downloading genomic fasta sequence and annotation in GFF format for all annotated leopard genomes:
`datasets download genome taxon 'panthera pardus' --annotated --include genome,gff3 --filename leopard.zip`

To download genome data for other taxonomic groups, you can substitute 'panthera pardus' with another taxonomic name or NCBI Taxonomy ID. 
Note that annotation in GFF format is only available for annotated genomes.

I hope that helps.

Best,
Eric

**Comment by recervictory** [comment]
Hi Eric (@ericcox1 ),

I hope this message finds you well. I appreciate your previous guidance on downloading genomic data for annotated leopard genomes. I have a query related to efficiently obtaining genomic data for multiple species and would be grateful for your assistance. Here's a breakdown:

- [ ] Bulk Taxon Name Retrieval:
  I am looking for a command or method to retrieve a list of all taxon names available in the NCBI database.
  The goal is to obtain this list in a structured way, possibly as folders, to facilitate organization.
  
-  [ ] Streamlining Genomic Data Download:
    Once I have the list of taxon names, I aim to download genomic data for each species.
    Is there a command or recommended approach to streamline this process and download genomic data for multiple species in bulk?

- [ ] Project Context:
  My project involves working with genomic data for a diverse set of species.
  Manually downloading data for each species is time-consuming; hence, I'm seeking an efficient way to automate or simplify the process.
  
```
# anything like this
for taxon in all_taxons
  datasets download genome taxon {taxon} --annotated --include genome,gff3 --filename {taxon}.zip

 ```

I value your expertise and any guidance you can provide on this matter would be greatly appreciated.

Thank you for your time and assistance.

Best regards,
Victor B

**Comment by artur-matysik** [comment]
Agree with @recervictory, that would be very useful feature!

**Comment by ericcox1** [comment]
Hi @recervictory,

I think a good place to start is by downloading all RefSeq reference genomes. Use taxon `1` to indicate that you want all taxa.

This will be a large dataset, close to 400 GB, so I recommend using rehydration, which allows you to resume the download if it is interrupted.

1. Download a dehydrated data package 
`datasets download genome taxon 1 --assembly-source refseq --reference --include genome,gff3 --dehydrated --filename all-refs.zip`
2. Unzip the downloaded package
`unzip all-refs.zip -d all-refs`
3. Rehydrate the extracted package
`datasets rehydrate --directory all-refs --gzip`

Let me know how it goes. I'm happy to help with next steps.

Best,
Eric
