### ISSUE TITLE
incorrect length for scaffold NC_018909.1 with datasets sequence report

### ISSUE THREAD

**Issue by conchoecia** [ncbi/datasets#301]
I was programatically checking that the record lengths in the genome nucleotide fasta files match the lengths as output by `datasets summary genome accession ASSEMBLY_ACCESSION --report sequence --as-json-lines`.

I found that there was one instance in which the reported scaffold length does not match the actual scaffold length. I am not yet sure if there are other entries that have a mismatch.

For example, `datasets summary genome accession GCF_000180615.1 --report sequence --as-json-lines | grep 'NC_018909.1'` shows a field `"length":13411861`. However, when I checked the record length with other tools it was `13411851` bases -- 10 bases fewer.

The genbank entry for this scaffold also says `13411851` bases: https://www.ncbi.nlm.nih.gov/nuccore/NC_018909.1?report=genbank

**Comment by ericcox1** [comment]
Hi @conchoecia, 

The nucleotide sequence length for `NC_018909.1` has been corrected:
```
datasets summary genome accession GCF_000180615.1 --report sequence --as-json-lines | grep 'NC_018909.1' | dataformat tsv genome-seq --fields refseq-seq-acc,seq-length
RefSeq seq accession	Seq length
NC_018909.1	13411851
```
Thanks again for opening this issue.

Best,
Eric
