### ISSUE TITLE
Download plasmids

### ISSUE THREAD

**Issue by erinyoung** [ncbi/datasets#304]
Is there a way to select and download the plasmids of refseq?

Refseq has reference plasmid sequences that can be downloaded from `https://ftp.ncbi.nlm.nih.gov/genomes/refseq/plasmid/`.

They are the `plasmid*genomic.fna.gz` files. 

I was hoping to find a similar functionality in datasets, but couldn't find it in the documentation.

**Comment by olearyna** [comment]
Hi [erinyoung](https://github.com/erinyoung),

At this time, NCBI Datasets only provides access to plasmids that are part of genome assembly set (GCA_ or GCF accessions) available through our genome service. I'll keep this feature in mind for future development.

Thanks,
Nuala 

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS
