### ISSUE TITLE
ncbi datasets cli not working (09/01/2024)

### ISSUE THREAD

**Issue by chriswyatt1** [ncbi/datasets#306]
Hi, 

We have been using ncbi datasets for 2 years and it works flawlessly, but this week it suddenly broke on seemingly Refseq IDs only. 

e.g. `datasets download genome accession GCF_000806365.1 --include genome,gff3`

Should print out the genome in fasta and the annotation in gff3. 

But after unzipping the folder we only get:

`inflating: README.md               
  inflating: ncbi_dataset/data/assembly_data_report.jsonl  
  inflating: ncbi_dataset/data/GCA_912469955.1/GCA_912469955.1_iVesVel2.1_alternate_haplotype_genomic.fna  
  inflating: ncbi_dataset/data/dataset_catalog.json `
  
This genome on NCBI website you can manually download the genome and GFF , does anyone know what has change since then?

Thanks,

Chris

**Comment by aboffin** [comment]
@chriswyatt1 What version are you using? The command works and the downloaded files contain the genomic fasta and gff files as expected.

`datasets download genome accession GCF_000806365.1 --include genome,gff3`:

```sh
Collecting 1 genome record [================================================] 100% 1/1
Downloading: ncbi_dataset.zip    50.2MB valid zip structure -- files not checked
Validating package [================================================] 100% 5/5
; unzip ncbi_dataset.zip 
Archive:  ncbi_dataset.zip
  inflating: README.md               
  inflating: ncbi_dataset/data/assembly_data_report.jsonl  
  inflating: ncbi_dataset/data/GCF_000806365.1/GCF_000806365.1_ASM80636v1_genomic.fna  cd 
  inflating: ncbi_dataset/data/GCF_000806365.1/genomic.gff  nc
  inflating: ncbi_dataset/data/dataset_catalog.json  
```

Head outputs:

```sh
; head ncbi_dataset/data/GCF_000806365.1/*
==> ncbi_dataset/data/GCF_000806365.1/GCF_000806365.1_ASM80636v1_genomic.fna <==
>NW_011887740.1 Fopius arisanus strain USDA-PBARC FA_bdor unplaced genomic scaffold, ASM80636v1 scaffold00001, whole genome shotgun sequence
CCatcaaatccatttttatgacGTGTGAAGATGAAGAAGTTGATGTTTGTCATTGGATAAAATTcctgagtgattttttt
ctgttgatcgGCGAACATCTTTTTAATCTTGACAACTACAACTGTTCACTTTACTAAAACTCCTGTCTGTGTGGAAATGA
AACTGTTTTTTGGGATTGaacaaattgaggaaaaaatgcgAGCGTATGAAGTTCAGCAATTACATGAAaacgatattttc
cattcgaatTCTCTTTGACGAATTAATTCCTGAATGATATTCACATTTCaatgttcattattatttttatggctTTTATA
GTATCACATCCGTTTTTCACATTCATTTGATTCggaatgtttgaaaaatttcgaggaatttatttatcatatatatataa
tttatatgaGTCATGCGCatgtataataattttcgacatttttttgaatgctTTCGTGATGAGGAATCACCCTTAATAGT
CATTTTGTGTCGGAATGATATTCGCAGcagttcaataaattaaatgaaataattgtccATAATTCTGGGGTAGAGTGTAA
CTTTACCCAATAACTTGAAGCAAATAATTCGTGAATGAATAGTCGCTGTTGAGAAAATGAATCTTGCTAGTAGATttaat
ttcggagatatttctgagaaattcaCAGAAACGCTAAGTTAATTTACTTGCTTTTACCACTTGACTATAGAATTAAATGT

==> ncbi_dataset/data/GCF_000806365.1/genomic.gff <==
##gff-version 3
#!gff-spec-version 1.21
#!processor NCBI annotwriter
#!genome-build ASM80636v1
#!genome-build-accession NCBI_Assembly:GCF_000806365.1
#!annotation-source NCBI Fopius arisanus Annotation Release 100
##sequence-region NW_011887740.1 1 5503185
##species https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=64838
NW_011887740.1	RefSeq	region	1	5503185	.	+	.	ID=NW_011887740.1:1..5503185;Dbxref=taxon:64838;Name=Unknown;chromosome=Unknown;gbkey=Src;genome=genomic;isolation-source=library from a single individual (USDA ID 24.2)%2C library from a pool of individuals that are full siblings of the first individual (USDA ID 24pool)%2C library from a pool of individual that are half siblings of the first individual (USDA ID 12pool);mol_type=genomic DNA;sex=male;strain=USDA-PBARC FA_bdor;tissue-type=whole organism
NW_011887740.1	Gnomon	gene	44308	292853	.	-	.	ID=gene-LOC105273548;Dbxref=GeneID:105273548;Name=LOC105273548;gbkey=Gene;gene=LOC105273548;gene_biotype=protein_coding
```

HTH

**Comment by chriswyatt1** [comment]
@aboffin
Thanks so much for your help. So we are using datasets version: 16.1.2 on both macM3 (arm64) and normal (amd64) containers (ecoflowucl/ncbi_download:v16.1.2-arm64  ,   ecoflowucl/ncbi_download:v16.1.2-amd64).

I realised in my about example, I sent the wrong ascension code, I meant using RefSeq identifiers such as : **GCA**_912469955.1 . All the GCF identifies work as normal.

It seems to be just with RefSeq IDs, that it no longer links up to a genome and a gff. Maybe the work around is only to use Genbank GCF ID names?

Thanks again,

Chris

**Comment by olearyna** [comment]
Hi @aboffin,

The GenBank genome assembly [GCA_912469955.1 ](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_912469955.1/)has not been annotated and won't have an associated gff3 file in the data package. GCA_912469955.1 genome submission is an alternate haplotype of [GCA_912470025.1 ](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_912470025.1/) which was annotated by NCBI.
