### ISSUE TITLE
Recent data missing when using `datasets download virus genome taxon`

### ISSUE THREAD

**Issue by corneliusroemer** [ncbi/datasets#309]
I’m somehow not getting sequences released on 2024-01-28 when downloading via:

```
datasets download virus genome taxon 10244 --filename data/ncbi_dataset.zip
```

despite them showing on NCBI virus: [https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/virus?SeqType_s=Nucleotide&VirusLineage_ss=Monke[…]-01-20T00:00:00.00Z%20TO%202024-01-30T23:59:59.00Z](https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/virus?SeqType_s=Nucleotide&VirusLineage_ss=Monkeypox%20virus,%20taxid:10244&Country_s=Germany&CreateDate_dt=2024-01-20T00:00:00.00Z%20TO%202024-01-30T23:59:59.00Z)

All sequences released up to 2024-01-15 do show up in the datasets download.

Today is the 30th of January so in my experience they should show up by now in datasets download.

Is there a syncing issue?

datasets version: 16.4.3 using ` Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]` downloaded via conda

**Comment by syntheticgio** [comment]
Hi @corneliusroemer ,

Thanks for reporting.  I'll go ahead and take a look into this and see what is going on.

-John

**Comment by corneliusroemer** [comment]
Hi @syntheticgio - I've been told on a Slack channel by NCBI staff that this is a known issue due to incremental update sync having broken down. They said they were aware already and have restarted the sync so this _should_ be fixed at some point soon.

**Comment by syntheticgio** [comment]
Thanks for the info @corneliusroemer (and for saving me some time!).  I'll track down the conversation that way I can make sure I can follow up after the sync is finished to try to verify it has indeed fixed the issue.

**Comment by corneliusroemer** [comment]
This may or may not work for you: https://cspheres.slack.com/archives/C0112BJ6W4F/p1706615616707629

**Comment by corneliusroemer** [comment]
I've been told it'll take a few days to fix incremental uploads for anyone who's coming across this issue.

**Comment by olearyna** [comment]
Thanks [corneliusroemer](https://github.com/corneliusroemer)

The virus data is up-to-date. Closing this issue. 

Nuala

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS
