### ISSUE TITLE
Request for additional attributes for Virus Data Report

### ISSUE THREAD

**Issue by joverlee521** [ncbi/datasets#310]
Hi NCBI datasets team,

Is there an official way to request additional metadata attributes to include in the Virus Data Report? 
If possible, I'd like to request the report to include the `strain` attribute.

---

Currently we are trying to use the NCBI Datasets CLI to download measles genomes via 
```
 datasets download virus genome taxon 11234 --no-progressbar --filename data/ncbi_dataset.zip
```

The downloaded Virus Data Report does not include the `strain` attribute, which we can potentially use to parse out dates for records as @jameshadfield [commented](https://github.com/nextstrain/measles/pull/10#discussion_r1473743542):

> For strain names following [the WHO schema](https://www.cdc.gov/measles/lab-tools/genetic-analysis.html), the "XX.YY" corresponds to
> 
>>    Date of rash onset if known, otherwise date of specimen collection by epidemiological week (1-53) and year.
>
> So, e.g., Accession JX187583, which doesn't have a date in our workflow, has sample name MVs/Parma.ITA/47.08 in [nuccore](https://www.ncbi.nlm.nih.gov/nuccore/JX187583) so it'd have date of 2008-11-XX | 2008-12-XX

**Comment by olearyna** [comment]
Hi [joverlee521](https://github.com/joverlee521),

NCBI Datasets retrieves its data directly from NCBI Virus. I've forwarded your message to them. They intend to incorporate strain information from GenBank records into their data sometime this year. It will then be added to the NCBI Datasets virus data report.

Thanks

Nuala

**Comment by joverlee521** [comment]
@syntheticgio Has the `strain` attribute been added to the outputs? 

I don't see any new columns in the output when running `datasets downloads` then `dataset format`.

**Comment by olearyna** [comment]
Hi [joverlee521](https://github.com/joverlee521),

The NCBI Datasets virus data report will automatically include the data from NCBI Virus once it becomes available, so no further action is required from our end. I also sent another message to the Virus team with your request.

Let me know if you have any other questions

Nuala

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS
