### ISSUE TITLE
Filter of results before downloading

### ISSUE THREAD

**Issue by fgvieira** [ncbi/datasets#313]
I am trying to download a representative genome for each species from refseq/genbank, and this repo looks very promising. However, I could not find a way to choose the best genome for each species.

There could either be a way to specify it on the command line or, alternatively, a way to filter the dehydrated files (to avoid unnecessary download). So, briefly, something like:

#### Download metadata
```
datasets download genome taxon 2759 --dehydrated --filename package.zip
```

#### Filter results
I would need a logical like:
For each species:
 - if > 1 genome
   - get if "representative genome", else get if "reference genome"
   - if > 1 genome
     - get if "Complete Genome", else get if "Chromosome", else get if "Scaffold", else get if "Contig"
      - if > 1 genome
        - get if "Major", else get if "Minor", else get if "Patch"
        - if > 1 genome
          - get latest

But I guess all files (`fetch.txt`, `data/assembly_data_report.jsonl`, and `data/dataset_catalog.json`) need to be filtered, no?

#### Download
Rehydrate files.

**Comment by ericcox1** [comment]
Thanks for opening this issue.

The best place to start would be to use the `--reference` flag like this:
```
datasets download genome taxon 2759 --reference --dehydrated --filename euk-ref-genomes.zip
```

This will give you a set of 15,673 genomes, representing 15,621 eukaryotic taxa.

For your information, you can use `--limit none` to quickly get the count of genomes using a particular flag or set of flags:
```
datasets summary genome taxon 2759 --reference --limit none
{"total_count": 15673}
```

Here's how I counted the number of eukaryotic taxa:
```
datasets summary genome taxon 2759 --reference --as-json-lines | dataformat tsv genome --fields organism-tax-id --elide-header | sort -u | wc -l
15621
```

Please let me know if this works for you. I'm happy to help you refine your filtering logic if necessary.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by fgvieira** [comment]
Hi Eric,

thanks for the quick reply.

What does the option `--reference` do? The help page says "Limit to reference genomes", but (e.g.) there are several human reference genomes; why is it only one returned? And how is it chosen? Running `datasets summary genome taxon 9606 --as-json-lines | wc -l` returns 1095 genomes.

From you numbers, there are more genomes than taxa. Does that mean that some species have more than one genome? How can I, using the criteria I mentioned above (and potentially others, like N50 or L50), further select/filter just one genome per species?

**Comment by ericcox1** [comment]
Hi @fgvieira,

>there are several human reference genomes; why is it only one returned?

There is a single human reference genome, [GRCh38](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000001405.40/). Note that this genome is identified with the green check in the [genome table](https://www.ncbi.nlm.nih.gov/datasets/genome/?taxon=9606).

>From you numbers, there are more genomes than taxa.

There are a small number of taxa for which we have multiple versions of genome assemblies marked as reference, for example:
```
datasets summary genome taxon 9662 --reference --as-json-lines | dataformat tsv genome --fields organism-tax-id,accession,assminfo-release-date
Organism Taxonomic ID	Assembly Accession	Assembly Release Date
9662	GCF_922984935.1	2021-12-19
9662	GCA_922984935.2	2022-03-23
```
In these cases, you could simple sort by release date and use the latest version:
```
datasets summary genome taxon 9662 --reference --as-json-lines | dataformat tsv genome --fields accession,assminfo-release-date --elide-header | sort -k2r | head -1
GCA_922984935.2	2022-03-23
```

I'm going to close this issue. Feel free to open a new issue if you have any other questions or feature requests.

Best,
Eric

**Comment by fgvieira** [comment]
Since I need to download several thousand genomes, I guess I need to use the dehydrated file (at least is what it says [here](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/)). How do I download the accessions after filtering?

I can download all Euk references dehydrated (`datasets download genome taxon 2759 --reference --dehydrated --filename euk-ref-genomes.zip`), but how can I filter before rehydrating? Is it possible to filter the files inside the zip file? Which one?
