### ISSUE TITLE
Partial (or cached) downloads

### ISSUE THREAD

**Issue by fgvieira** [ncbi/datasets#316]
Are partial (or cached) downloads supported? That is, after a first download of data, is it possible to re-run the same command and just download new data (both new versions but also new entries. For example:
- download all Euk WGS
- after 6 months, rerun command and only download:
  - newer WGS versions of existing taxa
  - WGS for taxa not present in the first run

The idea would be to avoid downloading data again.

**Comment by ericcox1** [comment]
Hi @fgvieira,

Thanks for opening this issue.

The ability to get only new data for a particular taxonomic group is something that we have discussed and that we are considering for future development.

In the meantime, I would suggest that you use the `--released-after` flag to only get new genomes released after a particular date, and avoid downloading the same data again.

For example, to download metadata for human genomes released after 12/1/2023:
```
datasets download genome taxon 9606 --released-after 12/01/2023 --include none --filename new-human.zip
Collecting 2 genome records [================================================] 100% 2/2
Downloading: new-human.zip    3.09kB valid zip structure -- files not checked
Validating package [================================================] 100% 3/3
```


Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
