### ISSUE TITLE
Questions on ZIP packages and JSON files

### ISSUE THREAD

**Issue by fgvieira** [ncbi/datasets#319]
First of all, I am really looking forward for this repo; it will make it much easier to access NCBI data!
However, there are some things I don't quite understand, but I might be missing something since I am mainly focused on downloading reference genomes:
- the hydrated file is a `zip` containing 3 json files:
  - `fetch.txt`: TSV with paths to download the data from and output file name
  - `data/assembly_data_report.jsonl`: metadata
  - `data/dataset_catalog.json`: type of files downloaded
- what is the difference between `datasets download --dehydrated` and `datasets summary`? The metadata is identical, except from case (camel vs snake case).

So, why not have the dehydrated file as a simple `json` with the content of `fetch.txt` included? This way `datasets summary` would be redundant, no need to unzip file before rehydrating, the user could freely edit/filter the json file, and it would be possible to perform incremental downloads (rehydrate a package to the same folder). I imagine something like:
1. Get metadata:
```
datasets download genome accession GCF_000001405.40 --dehydrated --filename human_GRCh38_dataset.json
```
2. Edit JSON
```
jq/python [...]
```
3. Rehydrate
```
datasets rehydrate --package human_GRCh38_dataset.json --directory my_human_dataset/
```

There would be some details about how to keep track of versions, but the `rehydrate` step could copy the `json` to the destination folder. This would then be checked to ensure all files are there and are not corrupted (when the metadata includes a checksum).

**Comment by ericcox1** [comment]
Hi @fgvieira,

Thanks for this feature request.

We appreciate the thought you put into this and I will discuss with the development team.

Given our limited resources, I'm going to close this ticket for now but we may reopen this issue in the future.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
