### ISSUE TITLE
Extra info in summary output

### ISSUE THREAD

**Issue by fgvieira** [ncbi/datasets#320]
Not all info available in `ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/assembly_summary_refseq.txt` is available from `dataset summary`. Would it be possible to also include:
- `species_taxid`
- `version_status`
- `release_type`
- `genome_rep`
- `group`
- `ftp_path`

thanks,

**Comment by olearyna** [comment]
Hi [fgvieira](https://github.com/fgvieira)

Thanks for the feedback

1. version_status - This info is retrievable from the "assembly_status" field in the summary genome output.

2. genome_rep - While we don't have a dedicated field for this data. If an assembly is partial, this information can be found within the 'genome_notes' section. For instance, in the case of GCA_900009995.2.

3. species_taxid - We currently provide the taxid of the genome submission. We are exploring options to include additional taxonomy information. Similarly, we are considering enhancing the taxonomy information available for the higher taxonomic 'group' names.

4. The ftp path is accessible through the API. You can find the URL here https://api.ncbi.nlm.nih.gov/datasets/v2alpha/genome/accession/GCF_000001405.40/links. We are also investigating making this accessible through the command-line tool.

5. release_type - At this time, we don't provide this. However, we appreciate your feedback and will consider these aspects for future improvements.

Please let me know if you have any questions.

Nuala

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS

**Comment by fgvieira** [comment]
Hi Nuala,

thanks for your reply. Just some follow up questions:

1. As far as I could see, `version_status` has value `["latest"]`, while `assembly_status` has values `["current", "previous", "suppressed"]`. Can I assume `"latest"` is the same as `"current"`?
2. Is this a controlled vocabulary field, or it can contain any kind of notes? If the former, what are the notes allowed?
3. Great! It would really be nice to have more taxonomic info.
4. Would it be possible to access it from the command line for several thousand genomes?
6. What about the `group`? Will it be included or dropped?

thanks,

**Comment by olearyna** [comment]
Hi [fgvieira](https://github.com/fgvieira)

Thanks for the questions,

1.	Yes current=latest
2.	Yes, here is a link to the list of genome notes https://www.ncbi.nlm.nih.gov/datasets/docs/v2/policies-annotation/genome-processing/genome_notes/
3.	We hope to have this available soon. 
4.	Yes, that would be our goal. 
5.	We plan to provide the full taxonomic tree. We won't maintain the 'group' field. 

Let me know if you have any further questions,

Nuala

**Comment by fgvieira** [comment]
Hi @olearyna,

just noticed that version `16.8.1` has a new command to query the taxonomy info. This is great, but it would be amazing if this info would be included on `datasets summary genome` for each accession's `taxid`. Are there any plans for this?

Not all taxonomic info would be relevant but, I think, at least:
```
            "taxonomy": {
                "children": [
                ],
                "classification": {
                },
                "parents": [
                ],
                "rank": "GENUS",
                "tax_id": 70447
            }
```
and maybe also:
```
                "current_scientific_name": {
                },
                "genomic_moltype": "dsDNA",
                "group_name": "green algae",
```

**Comment by olearyna** [comment]
Hi [fgvieira](https://github.com/fgvieira),

Thanks for the suggestions! We're not planning on implementing this immediately, but we'll definitely consider it alongside other feedback as we plan our future updates.

Nuala
