### ISSUE TITLE
Order of output datasets

### ISSUE THREAD

**Issue by alvanuffelen** [ncbi/datasets#323]
The return order of genome summaries are not the same as the input order.

`datasets summary genome accession --inputfile accessions.txt--as-json-lines --debug`

From the debug:

> "sort":[{"direction":"SORT_DIRECTION_ASCENDING","field":"organismName"},{"direction":"SORT_DIRECTION_DESCENDING","field":"isRefGenome"},{"direction":"SORT_DIRECTION_DESCENDING","field":"isRepGenome"},{"direction":"SORT_DIRECTION_DESCENDING","field":"isRefseq"},{"direction":"SORT_DIRECTION_ASCENDING","field":"accession"}]

To the best of my knowledge, this behavior is not documented. 
Unexpected outcomes may arise during downstream processing. 

Is it feasible to provide an option to enable or disable sorting?
[accessions.txt](https://github.com/ncbi/datasets/files/14433394/accessions.txt)
[output.json](https://github.com/ncbi/datasets/files/14433438/output.json)
[debug.txt](https://github.com/ncbi/datasets/files/14433441/debug.txt)

**Comment by ericcox1** [comment]
Hi @alvanuffelen,

Thanks for this feature request. 

>Is it feasible to provide an option to enable or disable sorting?

Although the option to disable sorting is feasible, this would _not_ result in the genome summaries being returned in the same order as the input order.

Although we do recognize the value in returning data in the same order as the input order, this feature is not easy to implement in our current system and we are unlikely to add this soon.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
