### ISSUE TITLE
"Large multi-isolate projects" field in `datasets summary genome` / `dataformat tsv` ?

### ISSUE THREAD

**Issue by paulimer** [ncbi/datasets#325]
Hi all,

Thanks (again) for this tool. What an improvement over Bio.Entrez and the like, great work. 

Looking into bacterial genomes, I'd like to exclude "large multi-isolate projects" from the genomes I want to download, as is possible on the [NCBI assembly](https://www.ncbi.nlm.nih.gov/assembly) website. I establish a list looking at all assemblies available in a taxon with  `datasets summary genome taxon` (then converted via the `dataformat` command). But neither command allow to exclude those assemblies (or display which are concerned in the second case). 

Have I missed something ? Has this tag maybe lost its meaning with time ? I think the GTDB uses it (at least it is mentioned in their [2022 paper](https://doi.org/10.1093/nar/gkab776)).

**Comment by ericcox1** [comment]
Hi @paulimer,

Thanks for this feature request.

We will consider this for future development.

In the meantime, you can exclude genomes from "large multi-isoalte projects" using `grep`:
```
datasets summary genome taxon 'salmonella bongori' --as-json-lines | dataformat tsv genome --fields accession,assminfo-notes --elide-header | grep -v 'from large multi-isolate project'
```

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by paulimer** [comment]
Thanks a lot for you answer ! I did not think that it was in assminfo-notes ! 
Have a good day

**Comment by paulimer** [comment]
Thank you very much ! I'll give it a try.
