### ISSUE TITLE
Feature Request:  bgzip option

### ISSUE THREAD

**Issue by genignored** [ncbi/datasets#327]
Downloading genomes from NCBI using datasets is immensely helpful.  However, when downloading large numbers of genomes, it is important to keep them compressed.  Currently, the only documented method to download genomes compressed is using the --gzip option.  

Samtools faidx, and several other tools, will only accept bgzipped files instead of gzipped.  is it possible to update datasets to allow for use of the bgzip library instead?

**Comment by ericcox1** [comment]
Hi @genignored,

Thank you for this feature request.

Unfortunately, we don't have the resources to implement this now, so I'm going to close this issue.

We will re-open this issue it if this feature is selected for development in the future.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
