### ISSUE TITLE
request for changelog - do not understand release notes

### ISSUE THREAD

**Issue by conchoecia** [ncbi/datasets#334]
Hello, just wanted to pitch in in relation to this question from two years ago: https://github.com/ncbi/datasets/issues/199

It seems like there are a few new changes that have been added in the last few months. It isn't really clear from the release notes what the new features are, or if the implementation of new features will change the syntax of the CLI. I just wanted to throw my proverbial vote in for some sort of change log describing changes to the CLI that will impact users.

That is all! Thank you for continuing development of these helpful tools.

**Comment by olearyna** [comment]
Hi [conchoecia](https://github.com/conchoecia),

Thanks for the feedback! We'll look into improving the release notes and consider introducing a change log.

Nuala
