### ISSUE TITLE
Download behind a proxy

### ISSUE THREAD

**Issue by poeli** [ncbi/datasets#34]
Hello,

I was running the example provided in `ncbi-datasets-virus.ipynb` to test Python API but failed to download genomes via `virus_api.virus_genome_download()`. Turned out I didn't have proper proxy settings with the API. After digging into the library, I found the proxy settings were hardcoded to `None` in `ncbi/datasets/configuration.py`. Is there a way I can use python API behind a proxy server?

Thanks for your help!

**Comment by BradHolmes** [comment]
Hi,

The `Configuration` class allows you to override attributes.  

I haven't tested this, but I would try something like:

```
my_config = ncbi.datasets.Configuration()
my_config.proxy = '...'  # Whatever proxy you need.

api_client = ApiClient(configuration=my_config)
virus_api = ncbi.datasets.VirusApi(api_client)
```

**Comment by poeli** [comment]
Great! Thank you so much Brad.
