### ISSUE TITLE
invalid or unsupported assembly accession: NC_001740

### ISSUE THREAD

**Issue by ggl2151** [ncbi/datasets#341]
Hello, I encountered a problem when running the following command using this software: "/project/GGL/datasetsdownload/datasets download genome accession NC_001740 --filename NC_001740.zip". The problem is "Error: invalid or unsupported assembly accession: NC_001740".

As shown in the image below, this sequence is for a plasmid sequence. 
![微信截图_20240401104152](https://github.com/ncbi/datasets/assets/74592616/c4293aaa-64e2-4cd0-9c4b-8590cf57e5c4)

I want to ask if the genome accession only includes assembly accessions or does it also include accessions for plasmids like this?

Thank you very much

**Comment by mtntsuchiya** [comment]
Hi,  
Thank you for using `datasets` and reaching out about this issue you found. 

Currently, datasets only supports download of genomes by taxon, BioProject accession or Assembly accession (accessions starting in GCA or GCF). If a plasmid is part of an assembly, you can also download it. For the other cases, you can find them here: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/plasmid/ 

Best,
Mirian

Mirian T. N. Tsuchiya, Ph.D.
Bioinformatics Data Wrangler (contractor)
NCBI Datasets (NCBI/NLM/NIH)
(she/her/hers)
