### ISSUE TITLE
Unable to locate the source code

### ISSUE THREAD

**Issue by ialbert** [ncbi/datasets#345]
I may have misread the page, but I could not locate the tool's source code.

From the binary, it seems to be written in Go.

Is this tool a closed-source software?

**Comment by ialbert** [comment]
moved it to a discussion.

**Comment by ialbert** [comment]
https://github.com/ncbi/datasets/discussions/346

**Comment by olearyna** [comment]
Hi [ialbert](https://github.com/ialbert),

The tool isn't closed-source; we simply haven't made it publicly available yet. We do intend to release it, though we don't have a fixed timeline for this yet. And yes, it's developed in Go.
You can build your own client library in any language using the NCBI Datasets OpenAPI 3.0 specification. You can find more information here: [NCBI Datasets API Documentation](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/languages/).

Nuala

Nuala A. O'Leary, PhD
Product Owner, NCBI Datasets
National Center for Biotechnology Information, NLM, NIH, DHHS

**Comment by ialbert** [comment]
It is not correct to claim that a software to be open source when it is not actually available. It makes no sense to say: it is open source, but we don't show you the code. .

One of the essential ingredients of open source means is that the source code is visible to the public.

Basically, what I think you are saying here that at some point (in the future), you intend to release the code as an open source software, but there is no timeline and in the meantime as of yet the software is closed source. 

Your licensing is really odd, actually; it does not follow the standards that scientists use and, as such, sets the wrong example.

It lacks transparency, it does not allow others to build upon it, it does not promote learning etc.

I believe that you are not following the rules when publishing closed-source software.
