### ISSUE TITLE
Accessing annotation from nuccore sequences

### ISSUE THREAD

**Issue by manulera** [ncbi/datasets#348]
Hello,

I was wondering if it is planned to ever be able to access annotations in non-assembly sequences. I am thinking of the particular example of pombe, where the mitochondrial chromosome is currently not part of the assembly (more on [this issue](https://github.com/pombase/curation/issues/3690)).

I guess this can be problematic since probably the API relies on the presence of unique `locus_tag`s on features in the annotated sequences, and nuccore sequences don't have these (e.g. [MK618072.1](https://www.ncbi.nlm.nih.gov/nuccore/MK618072.1/), despite it being a mitochondrial chromosome).

**Comment by olearyna** [comment]
Hi [manulera](https://github.com/manulera),

We are currently developing a new organelle data package, which will feature organelles not that are not part of an assembled genome. Initially, our focus will be on RefSeq annotated organelles, with plans to integrate GenBank organelles (such as [MK618072.1](https://www.ncbi.nlm.nih.gov/nuccore/MK618072.1/)) at a later stage.

Thanks,
Nuala
