### ISSUE TITLE
Unable to download PRJNA798058

### ISSUE THREAD

**Issue by icyjayd** [ncbi/datasets#351]
**Describe the bug**
I am unable to download the samples from [this BioProject](https://www.ncbi.nlm.nih.gov/biosample?LinkName=bioproject_biosample_all&from_uid=798058) (BioProject ID PRJNA798058) as given by [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10680783/). When I try, I receive this error: `Error: No assemblies found that match selection`. 

**To Reproduce**
Steps to reproduce using the curl installation (version 16.12.1):
1. cd into directory containing executable
2. Type `./datasets download genome accession PRJNA798058`
3. Press enter

Steps to reproduce using the conda installation (version 14.3.0)
1. Activate conda environment where `ncbi-datasets-cli` is installed
2. Type `datasets download genome accession PRJNA798058`
3. Press enter

**Expected behavior**
I expected the BioProject to be downloaded into the current directory.

**Comment by corneliusroemer** [comment]
A bioproject accession is not the type of accession expected here.

You need an assembly accession here.

I guess the error could be slightly clearer but this is AFAICT not a bug (I'm just a fellow user not a maintainer)

**Comment by icyjayd** [comment]
That is very unclear. [This page](https://ncbiinsights.ncbi.nlm.nih.gov/2021/01/05/bioproject-datasets/) says I should be able to download data by "BioProject accession." When I access the data [here](https://www.ncbi.nlm.nih.gov/biosample?LinkName=bioproject_biosample_all&from_uid=798058), it is titled "Links from BioProject." What is the BioProject accession if not the code that links the data to the BioProject?

**Comment by olearyna** [comment]
Hi [icyjayd](https://github.com/icyjayd),

You can only download **assembled genomes** by BioProject ID. There are no assembled genome for BioProject ID PRJNA798058. Please refer to this [issue ](please review this issue: https://github.com/ncbi/datasets/issues/287)for suggestions on getting SRA data for a BioProject ID.  Sorry for the confusion, we'll work on improving our documentation to make this clearer. 

Regards,
Nuala

**Comment by ericcox1** [comment]
Hi @icyjayd,

Thanks for creating this issue. We are looking at how we can better communicate the types of data that are available through NCBI Datasets.

For your original issue description:
>I am unable to download the samples from [this BioProject](https://www.ncbi.nlm.nih.gov/biosample?LinkName=bioproject_biosample_all&from_uid=798058) (BioProject ID PRJNA798058) as given by [this paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10680783/). When I try, I receive this error: Error: No assemblies found that match selection.

Are you primarily interested in BioSample data, as in the record shown in the attached screenshot?

Or are you interested in the associated SRA read data? Or perhaps both?

I look forward to hearing from you soon.

Best,
Eric
<img width="867" alt="Screenshot 2024-05-13 at 9 26 44 AM" src="https://github.com/ncbi/datasets/assets/36059326/e3e64c9b-333f-4ea2-9807-385677f4babf">
