### ISSUE TITLE
Missing `assembly_info.submitter` field (assembly record)

### ISSUE THREAD

**Issue by muffato** [ncbi/datasets#355]
Hello,

On [Datasets](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_964027075.1/), the GCA_964027075.1 record is missing its submitter field, even though it's there on the [legacy page](https://www.ncbi.nlm.nih.gov/assembly/GCA_964027075.1/?shouldredirect=false).

It's also missing from the JSON
```
datasets summary genome accession GCA_964027075.1
```

Best,
Matthieu

**Comment by ericcox1** [comment]
Hi @muffato,

Thanks for opening this issue. We fixed the underlying problem and the Datasets page ([GCA_964027075.1](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_964027075.1/)) should be populated with the submitter information later today or tomorrow.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by muffato** [comment]
Confirmed on my end. Thank you very much @ericcox1 !
