### ISSUE TITLE
Getting error Error: Internal error (invalid zip archive). Please try again

### ISSUE THREAD

**Issue by corneliusroemer** [ncbi/datasets#356]
### Before opening an issue, please:

- [ ] Make sure you are using the latest version using `datasets --version` (not on latest version as not yet on bioconda)

**Describe the bug**
Getting the following error message which doesn't explain how I can fix the problem:

```
Error: Internal error (invalid zip archive). Please try again
```

**To Reproduce**

```
$ datasets download virus genome taxon 186538             --no-progressbar             --filename results/ncbi_dataset.zip

New version of client (16.15.0) available at https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets
Error: Internal error (invalid zip archive). Please try again
```

**Expected behavior**
Clear error message that explains _why_ I get an invalid zip archive and how to fix it.

I'll try to capture `--debug` output

**Comment by corneliusroemer** [comment]
Here are the logs:
[error.txt](https://github.com/ncbi/datasets/files/15269516/error.txt)

**Comment by corneliusroemer** [comment]
Still getting this error stochastically (not every time, but regularly enough to notice in logs).

**Comment by ericcox1** [comment]
Thanks @corneliusroemer, we're investigating.

**Comment by joverlee521** [comment]
Seeing the [same error for mpox](https://github.com/nextstrain/mpox/actions/runs/9034936459/job/24828636568#step:5:268). 
```
[batch] [2024-05-10T16:18:17+00:00]         datasets download virus genome taxon 10244             --no-progressbar             --filename data/ncbi_dataset.zip
[batch] [2024-05-10T16:18:17+00:00]         
[batch] [2024-05-10T16:18:18+00:00] New version of client (16.15.0) available at https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets
[batch] [2024-05-10T16:20:03+00:00] Error: Internal error (invalid zip archive). Please try again
```

**Comment by ericcox1** [comment]
Hi @joverlee521, Are you still seeing the same issue today?

**Comment by joverlee521** [comment]
Hi @ericcox1, no longer seeing the issue today. The dataset for mpox has been downloading just fine over the last 2 days.

**Comment by ericcox1** [comment]
We believe these download problems were caused by a temporary problem that has been resolved. @corneliusroemer @joverlee521 please feel free to open a new issue if you see this problem again.

Best,
Eric

**Comment by corneliusroemer** [comment]
I'm getting the error again for mpox sadly

```
New version of client (16.16.0) available at https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-arm64/datasets.
Error: Internal error (invalid zip archive). Please try again
```
