### ISSUE TITLE
`--debug` dumps a lot of binary to stderr

### ISSUE THREAD

**Issue by corneliusroemer** [ncbi/datasets#362]
When adding the `--debug` flag as in `datasets download virus genome taxon 186538   --no-progressbar  --filename results/ncbi_dataset.zip    --debug` the initial output (a log of HTTP requests and responses) is helpful - but at some point when one gets the actual results, the stderr gets flooded with binary (probably contents of the zip I'm requesting).

This makes it quite difficult to review the debug results post run. Would it be possible to truncate long HTTP responses after a certain threshold? Though I guess the following works: ` --debug >debug.log 2>&1`

Debug logs are output to stderr, so one needs to make sure to redirect stderr into a file to prevent the flooding.

Example output (it's 100k more lines of binary like this)

<img width="2528" alt="image" src="https://github.com/ncbi/datasets/assets/25161793/b6b84ca6-a921-4867-b664-af7644574361">

**Comment by ericcox1** [comment]
Hi @corneliusroemer, 

Thanks for opening this issue. This is a known bug that should have been fixed as of `16.16.0`. 

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
