### ISSUE TITLE
Minor typo for "documentaion" in unzipped datasets output

### ISSUE THREAD

**Issue by d33bs** [ncbi/datasets#364]
### Before opening an issue, please:

- [x] Make sure you are using the latest version using `datasets --version`
- [x] Review our [documentation](https://www.ncbi.nlm.nih.gov/datasets/docs/download-and-install/)

**Describe the bug**

Thank you for the great work on this tool! I noticed a small typo in zipped content for the word "documentation". This appears in the unzipped output from using the `datasets` tool under the first/top-level `README.md` file within the unzipped output. I noticed this via the Linux version and using the `download genome taxon ...` options (unsure if this applies everywhere).

There's a section which currently includes "documentaion" as a minor typo:

```markdown
### Where can I find NCBI Datasets documentation?

Visit the NCBI Datasets documentaion pages:
https://www.ncbi.nlm.nih.gov/datasets/docs/
```

**To Reproduce**

1. Install latest datasets: `https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/v2/linux-amd64/datasets`
1. Download a dataset: `datasets download genome taxon 'Escherichia coli' --reference --filename download.zip`
2. Unzip the output: `unzip download.zip -d download`
3. Check the README for the mispelling: `cat download/README.md | grep 'documentaion'`

**Expected behavior**

Minor spelling correction.

### Thank you

Thanks for your feedback--your bug reports help improve NCBI Datasets.

**Comment by ericcox1** [comment]
Hi @d33bs,

Thanks for reporting this typo. We'll get this fixed sometime this week.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by d33bs** [comment]
Thank you @ericcox1 !

**Comment by ericcox1** [comment]
Hi @d33bs,

This typo has been fixed in production.

Thanks again for your bug report.

Best,
Eric

**Comment by d33bs** [comment]
Awesome turnaround! Thanks @ericcox1 !
