### ISSUE TITLE
Getting incorrect error: "186538 appears to be an invalid tax name"

### ISSUE THREAD

**Issue by corneliusroemer** [ncbi/datasets#367]
### Before opening an issue, please:

Version: 16.17.1

**Describe the bug**

I get an incorrect error from datasets CLI:

```bash
$ datasets download virus genome taxon 186538             --no-progressbar             --filename results/ncbi_dataset.zip             --api-key REDACTED
Error: 186538 appears to be an invalid tax name.  This could be due to unexpected special characters.
Use datasets download virus genome taxon <command> --help for detailed help about a command.
```

186538 is definitely a valid taxon id. I've been using this command for a long time, and am only now getting this error.

See: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=186538&lvl=3&lin=f&keep=1&srchmode=1&unlock

I got this error on a server. Now when running locally (with version 16.7.0) I get: `Error: 500 Internal Server Error`

Looking at more server logs, I see that all sorts of taxon ids are reported as invalid, including `3048448` (west nile)

**Comment by olearyna** [comment]
Hi @corneliusroemer,

Thanks for opening the issue. We had a temporary glitch. It should be working now. 

Thanks

Nuala
