### ISSUE TITLE
Regression: False error "3048448 appears to be an invalid tax name" for all taxons I've tried

### ISSUE THREAD

**Issue by corneliusroemer** [ncbi/datasets#373]
It seems the bug described previously in #367 and fixed for a while is now back:

```
❯ datasets download virus genome taxon 3048448             --no-progressbar             --filename results/ncbi_dataset.zip             --api-key REDACTED
Error: 3048448 appears to be an invalid tax name.  This could be due to unexpected special characters.

Use datasets download virus genome taxon <command> --help for detailed help about a command.
```

Getting it locally and on a server.

**Comment by ericcox1** [comment]
Hi @corneliusroemer,

Thanks for opening this issue. We experienced a temporary outage of our taxonomy data that is now resolved. Please try again and let me know if this problem persists.

Best,
Eric

**Comment by corneliusroemer** [comment]
Yep, it works now.

Can you maybe try to wrap a taxonomy outage in such a way that it doesn't sound like user error?

It seems you assume that if you don't get anything back from the API it's user error, when in fact that's not necessarily the case.

You could also make the error more open ended: saying it could be that the taxon doesn't exist or that the taxonomy API is down

**Comment by alvanuffelen** [comment]
I'm experiencing the same issue right now. Is there a site where we can check for outages?

**Comment by olearyna** [comment]
Hi [alvanuffelen](https://github.com/alvanuffelen),

Thanks for reaching out! We're currently aware of the issue and are actively working on a solution. Unfortunately, we don't have a specific site for checking outages at the moment, but we'll keep this thread updated with any progress or fixes.

Nuala

**Comment by olearyna** [comment]
Hi [alvanuffelen](https://github.com/alvanuffelen),

The issue is fixed. Please let us know if there are any other problems.

Nuala

**Comment by peradastra** [comment]
Also having this issue...


```
(db-env) perasperaadastra@MacBook-Pro-(2) data % datasets summary taxonomy taxon human
human appears to be an invalid tax name.  This could be due to unexpected special characters.

No valid taxons provided for summary - exiting
```
