### ISSUE TITLE
Gray background on openAPI docs if system dark mode is on (MacOS)

### ISSUE THREAD

**Issue by manulera** [ncbi/datasets#376]
If I go to the openAPI docs https://www.ncbi.nlm.nih.gov/datasets/docs/v2/reference-docs/rest-api/ with darkmode activated in MacOS (Sonoma 14.5), the background of the docs is set to gray and it's very hard to see the content (see screenshot)

<img width="470" alt="Screenshot 2024-06-17 at 14 30 42" src="https://github.com/ncbi/datasets/assets/22526102/e7f34440-dcc6-47ce-a81f-f53f0ae74676">

This happens in chrome and firefox, and goes away if I reload the page with the system darkmode switched off.

I don't know if this changed when I updated the OS or something changed in the page.

**Comment by olearyna** [comment]
Hi [manulera](https://github.com/manulera),

Thanks for reporting this! We're looking into it and hopefully have a fix soon. 

Nuala

**Comment by ericcox1** [comment]
Hi @manulera,

This has been fixed. Thanks again for opening this issue.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)

**Comment by manulera** [comment]
Amazing! Thanks
