### ISSUE TITLE
datasets RefSeq download does not retrieve all data

### ISSUE THREAD

**Issue by tallnuttrbgv** [ncbi/datasets#382]
Hi,

using the following:

datasets download genome accession GCA_018135685.1 --include gff3,rna,cds,protein,genome

for a RefSeq genome, but the command only retrieves the fasta assembly, no annotation., cds or proteins.

Thanks.

**Comment by olearyna** [comment]
Hi [tallnuttrbgv](https://github.com/tallnuttrbgv)

Thanks for opening this issue. The genome accession [GCA_018135685.1](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_018135685.1/) has not been annotated and therefore does not have an option to retrieve the gff, rna, cds or protein files.

Let me know if you have any other questions,

Nuala
