### ISSUE TITLE
Missing assembly

### ISSUE THREAD

**Issue by muffato** [ncbi/datasets#391]
### Before opening an issue, please:

- [x] Make sure you are using the latest version using `datasets --version`
- [x] Review our [documentation](https://www.ncbi.nlm.nih.gov/datasets/docs/download-and-install/)

Datasets is missing an assembly, GCA_964205305.1, that is available at <https://www.ncbi.nlm.nih.gov/assembly/GCA_964205305.1/?shouldredirect=false>

**To Reproduce**

```
$ datasets version
datasets version: 16.26.0
$ datasets summary genome accession GCA_964205305.1
{"total_count": 0}
```

**Expected behavior**

### Thank you

Thanks for your feedback--your bug reports help improve NCBI Datasets.

**Comment by muffato** [comment]
Same problem with `GCA_964205215.1`

**Comment by olearyna** [comment]
Hi [muffato](https://github.com/muffato),

The data files for this assembly are not fully processed yet. The FTP link on the legacy Assembly page is not available at this time. Once the files are made available, the assembly will be accessible in NCBI Datasets.

Let me know if you have any questions,

Nuala

**Comment by muffato** [comment]
Thank you for checking it, @olearyna
