### ISSUE TITLE
How we can enable datasets from firewall

### ISSUE THREAD

**Issue by chen1i6c04** [ncbi/datasets#392]
Hi

What ports and IP needs to be enable from firewall to use datasets to download genome data ?

I need these information due to security regulation.

Thanks

**Comment by syntheticgio** [comment]
Hi @chen1i6c04 ,

In order to download data using the datasets application you should only have to have access to make requests through port 443 (HTTPS).

John

**Comment by chen1i6c04** [comment]
Hi @syntheticgio 

So, `datasets` doesn't connect to a fixed URL or IP address to download data?

My IT department requires a URL or IP address to whitelist in the firewall.

Thanks
