### ISSUE TITLE
No genes annotated at the species level for taxon 2975324

### ISSUE THREAD

**Issue by farchaab** [ncbi/datasets#396]
**Describe the bug**
I am encountering an error when downloading genome summary for the 2975324 taxid

**Version**
```sh
$ datasets version
datasets version: 16.27.1
``` 

**To Reproduce**
```sh
$ datasets summary genome taxon 2975324
Error: There are no genes annotated at the species level for 'Streptococcus sp. FSL R7-0248' (taxid: '2975324') please use a subspecies tax name or ID.

Use datasets summary genome taxon <command> --help for detailed help about a command.
``` 

**Expected behavior**
Output summary data for the taxon

**Comment by olearyna** [comment]
Hi [farchaab](https://github.com/farchaab),

Thanks for opening this issue. We were able to reproduced the bug and are actively working on a fix. We hope to have it resolved and deployed in the next few days. For now you can download genome data for this taxid using the assembly accession. There is one assembled genome for [Streptococcus sp. FSL R7-0248](https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_037967965.1/).

`datasets summary genome accession  GCF_037967965.1`

Nuala

**Comment by ericcox1** [comment]
Hi @farchaab,

This bug has been fixed. The expected summary data is now returned for this taxon:
```
datasets summary genome taxon 2975324 --as-json-lines | dataformat tsv genome --fields accession,assminfo-name
Assembly Accession	Assembly Name
GCF_037967965.1	PS01774
GCA_037967965.1	PS01774
```

Thanks again for your report.

Best,
Eric
