### ISSUE TITLE
Allow multiple filters when using summary genome

### ISSUE THREAD

**Issue by Fabian-Bastiaanssen** [ncbi/datasets#408]
When running` datasets summary genome taxon "Bacillus" `or any other case where multiple taxa are under the same name, an error is returned, and the user is asked to use one of the taxids provided. 
It would be very helpful to use a second filter, maybe on a higher level, to avoid cases like this.  For example, `datasets summary genome taxon "Bacillus" taxon "Bacteria"` to exclude all non-bacterial entries. Alternatively a method to get all the options would work too, as long as it doesn't break pipelines.

Thank you

**Comment by ericcox1** [comment]
Hi @Fabian-Bastiaanssen,

Thanks for opening this issue.

In cases like this, where one taxonomic name maps to multiple taxonomic nodes, we recommend querying by taxid to be certain that you get the results that you want. 

For example, to get the bacterial genus Bacillus, use the taxid 1386:
```
datasets summary genome taxon 1386
```

>Alternatively a method to get all the options would work too, as long as it doesn't break pipelines.

Thanks for this suggestion. We may consider adding a feature like this in the future.

Best,
Eric
