### ISSUE TITLE
Provide a URL or IP address to whitelist in the firewall.

### ISSUE THREAD

**Issue by chen1i6c04** [ncbi/datasets#417]
Sorry I brought the question up again #392 

So, datasets doesn't connect to a fixed URL or IP address to download data?

My IT department requires a URL or IP address to whitelist in the firewall.

Thanks

**Comment by syntheticgio** [comment]
Hi,

Does 

```
https://api.ncbi.nlm.nih.gov/datasets/v2/.*
https://api.ncbi.nlm.nih.gov/datasets/v2alpha/.*
```

work?

**Comment by chen1i6c04** [comment]
Yes, it can work

Thanks very much
