### ISSUE TITLE
When downloading `virus genome taxon 10244` getting: `Error: Download error: stream error: stream ID 3; INTERNAL_ERROR; received from peer`

### ISSUE THREAD

**Issue by corneliusroemer** [ncbi/datasets#419]
Getting `Error: Download error: stream error: stream ID 5; INTERNAL_ERROR; received from peer` from multiple hosts, can't get it to work from anywhere.

```
$ datasets download virus genome taxon 10244 --no-progressbar --filename results/ncbi_dataset.zip
Error: Download error: stream error: stream ID 5; INTERNAL_ERROR; received from peer

Use datasets download virus genome taxon <command> --help for detailed help about a command.

❯ datasets version
datasets version: 16.33.0
```

Full logs with `--debug` (including Phid: `EEFD93355F94ED202DE9CA10.5.1`):

<details>

```
$ datasets download virus genome taxon 10244 --no-progressbar --filename results/ncbi_dataset.zip  --debug
2024/10/31 11:38:37
POST /datasets/v2/taxonomy/taxon_suggest HTTP/1.1
Host: api.ncbi.nlm.nih.gov
User-Agent: OpenAPI-Generator/1.0.0/go
Content-Length: 128
Accept: application/json
Content-Type: application/json
Ncbi-Phid: EEFD93355F94ED202DE9CA10
X-Datasets-Client: datasets-cli
X-Datasets-Client-Arch: arm64
X-Datasets-Client-Cmd: download virus genome taxon 10244 --no-progressbar --filename results/ncbi_dataset.zip --debug
X-Datasets-Client-Os: darwin
X-Datasets-Client-Version: 16.33.0
Accept-Encoding: gzip

{"exact_match":true,"tax_rank_filter":"higher_taxon","taxon_query":"10244","taxon_resource_filter":"TAXON_RESOURCE_FILTER_ALL"}

2024/10/31 11:38:37
HTTP/2.0 200 OK
Content-Security-Policy: upgrade-insecure-requests
Content-Type: application/json
Date: Thu, 31 Oct 2024 10:38:37 GMT
Grpc-Metadata-Via: h2 linkerd
Ncbi-Phid: EEFD93355F94ED202DE9CA10.1.1
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Datasets-Version: 16.33.0
X-Ua-Compatible: IE=Edge
X-Xss-Protection: 1; mode=block


2024/10/31 11:38:37
POST /datasets/v2/taxonomy HTTP/1.1
Host: api.ncbi.nlm.nih.gov
User-Agent: OpenAPI-Generator/1.0.0/go
Content-Length: 51
Accept: application/json
Content-Type: application/json
Ncbi-Phid: EEFD93355F94ED202DE9CA10
X-Datasets-Client: datasets-cli
X-Datasets-Client-Arch: arm64
X-Datasets-Client-Cmd: download virus genome taxon 10244 --no-progressbar --filename results/ncbi_dataset.zip --debug
X-Datasets-Client-Os: darwin
X-Datasets-Client-Version: 16.33.0
Accept-Encoding: gzip

{"returned_content":"METADATA","taxons":["10244"]}

2024/10/31 11:38:38
HTTP/2.0 200 OK
Content-Security-Policy: upgrade-insecure-requests
Content-Type: application/json
Date: Thu, 31 Oct 2024 10:38:38 GMT
Grpc-Metadata-Via: h2 linkerd
Ncbi-Phid: EEFD93355F94ED202DE9CA10.2.1
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Datasets-Version: 16.33.0
X-Ua-Compatible: IE=Edge
X-Xss-Protection: 1; mode=block


2024/10/31 11:38:38
POST /datasets/v2/taxonomy HTTP/1.1
Host: api.ncbi.nlm.nih.gov
User-Agent: OpenAPI-Generator/1.0.0/go
Content-Length: 51
Accept: application/json
Content-Type: application/json
Ncbi-Phid: EEFD93355F94ED202DE9CA10
X-Datasets-Client: datasets-cli
X-Datasets-Client-Arch: arm64
X-Datasets-Client-Cmd: download virus genome taxon 10244 --no-progressbar --filename results/ncbi_dataset.zip --debug
X-Datasets-Client-Os: darwin
X-Datasets-Client-Version: 16.33.0
Accept-Encoding: gzip

{"returned_content":"COMPLETE","taxons":["10244"]}

2024/10/31 11:38:38
HTTP/2.0 200 OK
Content-Security-Policy: upgrade-insecure-requests
Content-Type: application/json
Date: Thu, 31 Oct 2024 10:38:38 GMT
Grpc-Metadata-Via: h2 linkerd
Ncbi-Phid: EEFD93355F94ED202DE9CA10.3.1
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Datasets-Version: 16.33.0
X-Ua-Compatible: IE=Edge
X-Xss-Protection: 1; mode=block


2024/10/31 11:38:38
POST /datasets/v2/taxonomy HTTP/1.1
Host: api.ncbi.nlm.nih.gov
User-Agent: OpenAPI-Generator/1.0.0/go
Content-Length: 21
Accept: application/json
Content-Type: application/json
Ncbi-Phid: EEFD93355F94ED202DE9CA10
X-Datasets-Client: datasets-cli
X-Datasets-Client-Arch: arm64
X-Datasets-Client-Cmd: download virus genome taxon 10244 --no-progressbar --filename results/ncbi_dataset.zip --debug
X-Datasets-Client-Os: darwin
X-Datasets-Client-Version: 16.33.0
Accept-Encoding: gzip

{"taxons":["10244"]}

2024/10/31 11:38:39
HTTP/2.0 200 OK
Content-Security-Policy: upgrade-insecure-requests
Content-Type: application/json
Date: Thu, 31 Oct 2024 10:38:39 GMT
Grpc-Metadata-Via: h2 linkerd
Ncbi-Phid: EEFD93355F94ED202DE9CA10.4.1
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Datasets-Version: 16.33.0
X-Ua-Compatible: IE=Edge
X-Xss-Protection: 1; mode=block


2024/10/31 11:38:39
POST /datasets/v2/virus/genome/download HTTP/1.1
Host: api.ncbi.nlm.nih.gov
User-Agent: OpenAPI-Generator/1.0.0/go
Content-Length: 279
Accept: text/plain,application/zip
Content-Type: application/json
Ncbi-Phid: EEFD93355F94ED202DE9CA10
X-Datasets-Client: datasets-cli
X-Datasets-Client-Arch: arm64
X-Datasets-Client-Cmd: download virus genome taxon 10244 --no-progressbar --filename results/ncbi_dataset.zip --debug
X-Datasets-Client-Os: darwin
X-Datasets-Client-Version: 16.33.0
Accept-Encoding: gzip

{"annotated_only":false,"complete_only":false,"format":"tsv","geo_location":"","host":"","include_sequence":["GENOME"],"pangolin_classification":"","refseq_only":false,"released_since":"0001-01-01T00:00:00Z","taxon":"10244","updated_since":"0001-01-01T00:00:00Z","usa_state":""}

2024/10/31 11:38:39
HTTP/2.0 200 OK
Content-Disposition: attachment; filename=ncbi_dataset.zip
Content-Security-Policy: upgrade-insecure-requests
Content-Type: application/zip
Date: Thu, 31 Oct 2024 10:38:39 GMT
Grpc-Metadata-Logging-Activity: download
Grpc-Metadata-Logging-Annotated_only: False
Grpc-Metadata-Logging-Refseq_only: False
Grpc-Metadata-Logging-Service: virus
Grpc-Metadata-Logging-Taxon: 10244
Grpc-Metadata-Via: h2 linkerd
Ncbi-Phid: EEFD93355F94ED202DE9CA10.5.1
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Encoding
X-Datasets-Version: 16.33.0
X-Ua-Compatible: IE=Edge
X-Xss-Protection: 1; mode=block


Error: Download error: stream error: stream ID 3; INTERNAL_ERROR; received from peer

Use datasets download virus genome taxon <command> --help for detailed help about a command.
```

</details>

**Comment by corneliusroemer** [comment]
I can't reproduce for those taxons, though they have possibly smaller total download sizes, so that might explain why mpox is different?

- 3052518 (Ebola Zaire)
- 3048448 (Ebola Sudan)
- 3052460 (West Nile)
- 3052462 (CCHF)

**Comment by corneliusroemer** [comment]
Thanks so much @ericcox1! The problem no longer appears for me!

**Comment by corneliusroemer** [comment]
The problem seems to have resurfaced, we got this in the nextstrain mpox pipeline yesterday:

```
[batch] [2024-11-13T17:15:36+00:00] rule fetch_ncbi_dataset_package:
[batch] [2024-11-13T17:15:36+00:00]     output: data/ncbi_dataset.zip
[batch] [2024-11-13T17:15:36+00:00]     jobid: 5
[batch] [2024-11-13T17:15:36+00:00]     benchmark: benchmarks/fetch_ncbi_dataset_package.txt
[batch] [2024-11-13T17:15:36+00:00]     reason: Missing output files: data/ncbi_dataset.zip
[batch] [2024-11-13T17:15:36+00:00]     resources: tmpdir=/tmp
[batch] [2024-11-13T17:15:36+00:00]         datasets download virus genome taxon 10244             --no-progressbar             --filename data/ncbi_dataset.zip
[batch] [2024-11-13T17:15:36+00:00]         
[batch] [2024-11-13T17:16:16+00:00] Error: Download error: stream error: stream ID 3; INTERNAL_ERROR; received from peer
[batch] [2024-11-13T17:16:16+00:00] Use datasets download virus genome taxon <command> --help for detailed help about a command.
```

**Comment by ericcox1** [comment]
Hi @corneliusroemer,

Thanks for reopening this issue. I was able to reproduce this and we are investigating. I will let you know when a fix is ready.

Best,
Eric

**Comment by songshuang1996** [comment]
I get the same error using datasets 16.35.1 from the Ubuntu server and Mac.

datasets download genome taxon Acinetobacter --assembly-source refseq --include gbff --reference
Download error: stream error: stream ID 5; INTERNAL_ERROR; received from peer

**Comment by corneliusroemer** [comment]
While it had been fixed again for a few days, unfortunately I'm now getting it for things beyond mpox, also ebola-zaire, west-nile. 

Seems to have gotten worse unfortunately also based on the report from @songshuang1996

**Comment by pentamorfico** [comment]
Hi @ericcox1 @corneliusroemer @songshuang1996, I'm currently having the same issue with any given genome:

`Error: Download error: stream error: stream ID 5; INTERNAL_ERROR; received from peer`

**Comment by ericcox1** [comment]
Thank you @corneliusroemer and @pentamorfico, we are continuing to investigate.

@pentamorfico Could you please provide one example query that you are using?

**Comment by pentamorfico** [comment]
Hi @ericcox1, the issue is not happening anymore. I tried to replicate the error with the IDs that I was using and I was unable to get the same error again.

So I think everything is working now. I will paste here the IDs if I get the same error again.

**Comment by ericcox1** [comment]
Hi @corneliusroemer and @pentamorfico,

We made some updates to the virus genome download process that appears to fix this problem. I'm closing this issue.

-Eric

**Comment by corneliusroemer** [comment]
Thanks @ericcox1, I'll let you know if it ever comes back. We notice things pretty quickly due to using datasets for previews in Loculus 😀

**Comment by pentamorfico** [comment]
Amazing, thanks you so much!

**Comment by valery-shap** [comment]
Hi, @ericcox1 ,

I have the same error (Error: Download error: stream error: stream ID 737; INTERNAL_ERROR; received from peer) using 
datasets version: 16.40.1. The job was sent using slurm.
command was - 
datasets download genome taxon 562 --include genome,gff3 --filename ecoli.zip.
I found the zip file in the output directory, but I couldn't open it using unzip:
Archive:  ecoli.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ecoli.zip or
        ecoli.zip.zip, and cannot find ecoli.zip.ZIP, period.

**Comment by jmcribeiro** [comment]
Hi,

I had the same error  "errorINTERNAL_ERROR; received from peer"  runing from a windows or linux machine.

The command was:
datasets download genome taxon Wolbachieae --filename wolbachia_datasets.zip

and the output was:
Collecting 2,182 genome records [================================================] 100% 2182/2182
Downloading: wolbachia_datasets.zip    903kB errorINTERNAL_ERROR; received from peer

I also got this output in another run of the same command:

Collecting 2,182 genome records [================================================] 100% 2182/2182
Error: [gateway] Post "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/download": POST https://api.ncbi.nlm.nih.gov/datasets/v2/genome/download giving up after 11 attempt(s)

I will kwwp trying to download the genomes.

Thanks for your help,

Jose

**Comment by AlexanderThomasJulian** [comment]
Hello, @ericcox1,

It seems that this a more widespread issue than just viral genomes this time around. Does this have anything to do with the cuts and restructuring of the NIH?

Here is the debug message I obtained.

`datasets download genome taxon "encephalitozoon cuniculi" --include gbff --debug

Collecting 7 genome records [------------------------------------------------]   0% 0/7
2025/05/10 23:54:56 
HTTP/2.0 200 OK
Access-Control-Expose-Headers: X-RateLimit-Limit,X-RateLimit-Remaining
Content-Security-Policy: upgrade-insecure-requests
Content-Type: application/json
Date: Sun, 11 May 2025 04:54:55 GMT
Grpc-Metadata-Via: h2 linkerd
Ncbi-Phid: 4102B03BEE432A14296470FD.5.1.1
Server: Finatra
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Datasets-Version: undefined
X-Ncbi-Total-Count: 7
X-Ratelimit-Limit: 5
X-Ratelimit-Remaining: 0
X-Ua-Compatible: IE=Edge
X-Xss-Protection: 1; mode=block


2025/05/10 23:54:56 
POST /datasets/v2/genome/download HTTP/1.1
Host: api.ncbi.nlm.nih.gov
User-Agent: OpenAPI-Generator/1.0.0/go
Content-Length: 213
Accept: text/plain,application/zip
Content-Type: application/json
Ncbi-Phid: 4102B03BEE432A14296470FD
X-Datasets-Client: datasets-cli
X-Datasets-Client-Arch: amd64
X-Datasets-Client-Cmd: download genome taxon encephalitozoon cuniculi --include gbff --debug
X-Datasets-Client-Os: linux
X-Datasets-Client-Version: 18.1.0
Accept-Encoding: gzip

{"accessions":["GCA_027571585.1","GCA_000221285.2","GCA_000221265.2","GCA_000221245.2","GCA_001078035.1","GCF_000091225.2","GCA_000091225.2"],"hydrated":"FULLY_HYDRATED","include_annotation_type":["GENOME_GBFF"]}
Collecting 7 genome records [================================================] 100% 7/7
Error: [gateway] Post "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/download": POST https://api.ncbi.nlm.nih.gov/datasets/v2/genome/download giving up after 11 attempt(s)`

**Comment by olearyna** [comment]
Hi [AlexanderThomasJulian](https://github.com/AlexanderThomasJulian) and [jmcribeiro](https://github.com/jmcribeiro),

Thanks for your comments—and sorry to hear you were having trouble with the downloads. It looks like we experienced a network issue over the weekend, but everything should be working fine now. Please let us know if you run into any more issues!

Nuala
