### ISSUE TITLE
Overly specific taxon matching

### ISSUE THREAD

**Issue by Fabian-Bastiaanssen** [ncbi/datasets#435]
When running the command

datasets summary genome taxon "Nocardia alni"
I'd expect to get Nocardia alni, however, I get the results
Error: The taxon name 'Nocardia alni' has more than 1 exact match in taxonomy. Please pick one of these taxids:
Nocardia alni (species, taxid: 2815723)
Frankia alni (species, taxid: 1859)

If there is an exact match in the set, it should not suggest Frankia alni

**Comment by olearyna** [comment]
Hi [Fabian-Bastiaanssen](https://github.com/Fabian-Bastiaanssen),

Thank you for opening this issue. The name _Nocardia alni_ is the current scientific name for [Taxid: 2815723](https://www.ncbi.nlm.nih.gov/datasets/taxonomy/2815723/names/) , but it is also listed as a synonym for _Frankia alni_ ([Taxid: 1859)](https://www.ncbi.nlm.nih.gov/datasets/taxonomy/1859/names/). While our tool allows searching by names for convenience, when a name corresponds to multiple taxa, it will prompt you to select the correct Taxid. This approach ensures that you retrieve data for the specific organism you intended.

Let me know if you have any further questions.
Nuala
