### ISSUE TITLE
MIXS IDs on NCBI datasets

### ISSUE THREAD

**Issue by maxmaronna** [ncbi/datasets#46]
Hello,
I am interested in mapping MIXS IDs on NCBI datasets and to create a "NCBI subway visualization map". I did not find an unique sheet with all MIXS IDs in just one single tab (version 5), so I created one online: https://docs.google.com/spreadsheets/d/1O8UZ5Myqylpdpk94G_zo2r0LN1hwWvOzRQ0SHDDsQEM/edit?usp=sharing
Now, I did not find a proper sheet to map MIXS IDS on all NCBI metadata. Do you know if there is anything like this on any website (even outside the NCBI website)? Thanks in advance, maxmaronna.

**Comment by BradHolmes** [comment]
Hi,

I'm afraid there is nothing like this that we are aware of.  Sorry.

Brad

**Comment by maxmaronna** [comment]
Hello Brad,

Thanks for your answer. Do you have a sheet to share, with all possible metadata, considering NCBI Datasets-section Genomes: Genome, Bioproject, Assembly, Biosample, Nucleotide, SRA, Biocollection, Taxonomy? 

Thanks in advance, max

**Comment by ericcox1** [comment]
Hi Max, 

I think the best thing we can offer at this time would be the genome assembly and genome sequence report schemas, which describe the metadata available for the [NCBI Datasets Genome Data Package](https://www.ncbi.nlm.nih.gov/datasets/docs/data-packages/genome/).

[Genome assembly report schema](https://www.ncbi.nlm.nih.gov/datasets/docs/reference-docs/data-reports/genome-assembly/
)
[Genome sequence report schema](https://www.ncbi.nlm.nih.gov/datasets/docs/reference-docs/data-reports/genome-sequence/)

Best,
Eric

**Comment by maxmaronna** [comment]
Hi Eric, 
I am sorry for this late reply. 
Thanks a lot for the links. If NCBI is considering to work to align&map metadata definitions to MIxS_Darwin Core, I would like to help.

Best
max
