### ISSUE TITLE
information from GBFF missing in JSON

### ISSUE THREAD

**Issue by shrutivijayk** [ncbi/datasets#47]
Information like sequencing technology and submitter/author names etc. is available in the GBFF file. However, this information is missing from JSON files. GBFF files are harder to process programmatically compared to JSON. Can you please suggest any solutions for this missing information?
Thank you.

**Comment by ericcox1** [comment]
@shrutivijayk Thanks for your feedback. Could you please provide some more information about the type of data that you're interested in? Are you interested in SARS-CoV-2 genome data or genome data for another organism?
