### ISSUE TITLE
datasets cli not functional in minimal containers

### ISSUE THREAD

**Issue by mvdbeek** [ncbi/datasets#51]
Trying a couple of datasets commands I'm seeing this:
```
root@d43c3430b189:/test-data# datasets download genome taxon human --chromosomes 21
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87ec9a]

goroutine 1 [running]:
main/datasets/datasets.baseRetryPolicy(...)
	src/datasets/datasets/root.go:182
main/datasets/datasets.DefaultRetryPolicy(0xa35290, 0xc0000ba010, 0x0, 0xa2dfc0, 0xc00007ea80, 0x0, 0xc0001f6000, 0x203000)
	src/datasets/datasets/root.go:152 +0x7a
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc00011fc00, 0xc000099c20, 0x0, 0x0, 0x0)
	external/com_github_hashicorp_go_retryablehttp/client.go:597 +0x1f1
github.com/hashicorp/go-retryablehttp.(*RoundTripper).RoundTrip(0xc0000b03c0, 0xc0001c9600, 0xc0000b03c0, 0x0, 0x0)
	external/com_github_hashicorp_go_retryablehttp/roundtripper.go:44 +0x85
net/http.send(0xc0001c9600, 0xa2c8c0, 0xc0000b03c0, 0x0, 0x0, 0x0, 0xc0000be3a8, 0x8f2540, 0x1, 0x0)
	GOROOT/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xc0001de2a0, 0xc0001c9600, 0x0, 0x0, 0x0, 0xc0000be3a8, 0x0, 0x1, 0x0)
	GOROOT/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xc0001de2a0, 0xc0001c9600, 0x0, 0x0, 0x0)
	GOROOT/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	GOROOT/src/net/http/client.go:585
main/openapi_client.(*APIClient).callAPI(0xc0000ed1c0, 0xc0001c9600, 0x0, 0xc0000e2c00, 0x34)
	src/generated/openapi_client/client.go:188 +0x4d
main/openapi_client.(*GenomeApiService).GenomeMetadataByPost(0xc0000ed1c8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	src/generated/openapi_client/api_genome.go:1340 +0x46d
main/datasets/datasets.getAssemblyMetadataPage(0xc0000ed1c0, 0xc000129980, 0x3e8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	src/datasets/datasets/SummaryGenomeAccession.go:61 +0x105
main/datasets/datasets.getAssemblyMetadataWithPost(0xc000129980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	src/datasets/datasets/SummaryGenomeAccession.go:100 +0x194
main/datasets/datasets.glob..func7(0xd06d80, 0xc0001de180, 0x1, 0x3, 0x0, 0x0)
	src/datasets/datasets/DownloadGenomeTaxon.go:41 +0x10f
github.com/spf13/cobra.(*Command).execute(0xd06d80, 0xc0001de150, 0x3, 0x3, 0xd06d80, 0xc0001de150)
	external/com_github_spf13_cobra/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xd050a0, 0x4686c5, 0xc000000180, 0x200000003)
	external/com_github_spf13_cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	external/com_github_spf13_cobra/command.go:887
main/datasets/datasets.Execute()
	src/datasets/datasets/root.go:411 +0x31
main.main()
	src/cmd/datasets/main.go:10 +0x25
```
That is using https://quay.io/repository/biocontainers/ncbi-datasets-cli?tag=11.25.1&tab=tags, which is built using the package from conda-forge.
If I download the compiled binary from https://ftp.ncbi.nlm.nih.gov/pub/datasets/command-line/LATEST/linux-amd64/datasets 
I'm seeing
```
root@eec4fd0b41a1:/# ./datasets download genome taxon human --chromosomes 21
Error: No assembly available
```

Do you have any pointers on what is going on here ?

**Comment by mvdbeek** [comment]
After some digging the root cause seems to be missing or outdated root certificates. If you include `ca-certificates` in the conda-forge feedstock and run `export SSL_CERT_FILE=/usr/local/ssl/cacert.pem` things work ... . I've asked for advice in https://gitter.im/bioconda/Lobby?at=60e2f003457e19611a36aed6

**Comment by pmeric** [comment]
H Marius, without yet addressing your primary question here, it's a little odd that the binary you downloaded from ftp found no assemblies, it sounds like a glitch. Having said that, you probably want a slightly different command-line anyway, assuming you don't want to download _all_ human assemblies in a single package and instead are content for the current reference assembly:
`download genome taxon human --reference --chromosomes 21`

**Comment by mvdbeek** [comment]
I just copied the example from the help section of `datasets download genome taxon` ;).

> it's a little odd that the binary you downloaded from ftp found no assemblies, it sounds like a glitch.

Both issues are fixed by providing the SSL cert part with `export SSL_CERT_FILE=/usr/local/ssl/cacert.pem`, so I guess there's just some additional error handling in the official binary that is not in the version published on conda-forge.

**Comment by pmeric** [comment]
Note that the binary on ftp is updated with every software release, where the conda package is updated manually and intermittently.
Thanks for the SSL cert pointers, we'll get back to you on this soon
