### ISSUE TITLE
ImportError: cannot import name 'GenomeApi' from 'ncbi.datasets.openapi'

### ISSUE THREAD

**Issue by DDudka9** [ncbi/datasets#62]
**Im installed ncbi.datasets using -> pip install ncbi-datasets-pylib==12.13.1**
**I run it in PyCharm console (in virtual env with python 3.7; MacOS Mojave 10.14.6)**

def get_assemblies():
    import sys
    import zipfile
    import pandas as pd
    from pprint import pprint
    from datetime import datetime
    from collections import defaultdict, Counter
    from IPython.display import display
    import matplotlib.pyplot as plt
    plt.style.use('ggplot')
    try:
        import ncbi.datasets
    except ImportError:
        print('ncbi.datasets module not found. To install, run `pip install ncbi-datasets-pylib`.')

from ncbi.datasets.metadata.genome import get_assembly_metadata_by_bioproject_accessions

**This resulted in:**

Traceback (most recent call last):
  File "/Users/damian/anaconda3/envs/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-cf061ca14a6e>", line 1, in <module>
    from ncbi.datasets.metadata.genome import get_assembly_metadata_by_bioproject_accessions
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/damian/anaconda3/envs/py37/lib/python3.7/site-packages/ncbi/datasets/metadata/genome.py", line 6, in <module>
    from ncbi.datasets.openapi import GenomeApi as DatasetsGenomeApi
ImportError: cannot import name 'GenomeApi' from 'ncbi.datasets.openapi' (/Users/damian/anaconda3/envs/py37/lib/python3.7/site-packages/ncbi/datasets/openapi/__init__.py)

When I run these commands:

import ncbi.datasets
1. dir(ncbi.datasets) -> ['ApiAttributeError',
 'ApiClient',
 'ApiException',
 'ApiKeyError',
 'ApiTypeError',
 'ApiValueError',
 'Configuration',
 'GeneApi',
 'GenomeApi',
 'OpenApiException',
 'ProkaryoteApi',
 'TaxonomyApi',
 'VersionApi',
 'VirusApi',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'api_client',
 'configuration',
 'exceptions',
 'metadata',
 'model_utils',
 'openapi',
 'rest']

2. dir(ncbi.datasets.openapi) -> ['ApiAttributeError',
 'ApiClient',
 'ApiException',
 'ApiKeyError',
 'ApiTypeError',
 'ApiValueError',
 'Configuration',
 'OpenApiException',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'api',
 'api_client',
 'apis',
 'configuration',
 'exceptions',
 'model',
 'model_utils',
 'models',
 'rest']

**What am I missing? GenomeApi does not seem to be in openapi**

**Comment by ericcox1** [comment]
Hi DDudka9,

The bug should be fixed in the latest version of the python library: https://pypi.org/project/ncbi-datasets-pylib/12.13.2/

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
eric.cox@nih.gov

**Comment by DDudka9** [comment]
Hi Eric,

Thank you for fixing the bug. I have been also having an issue with using the API to get an older Mus musculus assembly using accession number : GCA_000001635.8
I get a file of about 800 bytes. Unfortunately my application requires that older assembly. By comparison, I have no problem getting a zip file of an assembly number : GCA_003336285.1.

Does the API work only with latest assemblies? 

Thank you for your help,

Damian
