### ISSUE TITLE
Cannot find reference 'GeneApi' in '__init__.py'

### ISSUE THREAD

**Issue by zivlang** [ncbi/datasets#74]
Hello.
After installing the python package "ncbi-datasets-pylib" I tried using one of the example codes.
One of the lines in the code is 
from ncbi.datasets.openapi import GeneApi as DatasetsGeneApi,
GenApi in this line gets the error message: "Cannot find reference 'GeneApi' in '__init__.py'".
Is this API under construction as of now?

**Comment by ericcox1** [comment]
Hi Zivlang,

Thanks for trying the NCBI Datasets python package and thanks for your feedback.

> One of the lines in the code is
> from ncbi.datasets.openapi import GeneApi as DatasetsGeneApi

This is a documentation error. The correct code is:
`from ncbi.datasets.openapi.api.gene_api import GeneApi`

Thanks for the report. We will update the documentation as soon as possible.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
eric.cox@nih.gov

**Comment by zivlang** [comment]
Great. Thanks.

בתאריך יום ו׳, 19 בנוב׳ 2021, 01:48, מאת Eric Cox ***@***.***
