### ISSUE TITLE
virus_api.virus_genome_download() - Improve documentation for geo_location param

### ISSUE THREAD

**Issue by DOH-PJG1303** [ncbi/datasets#77]
for the api client, the virus_api.virus_genome_download() has a parameter called "geo_location".  Documentation suggests that this parameter should be a string, but in the instance where you would like to filter down to a state specifically, you need to specify a list of strings.  For the state of washington, this looks like:
`geo_location = ['USA','Washington']`
I spent about 30 mins figuring this out using trial by error haha.

--------------

<img width="696" alt="image" src="https://user-images.githubusercontent.com/80795761/144682955-bb981598-c076-4936-a356-a849485ad3de.png">

--------------

Could you please add something that helps people understand that if you want state-specific information, they need to include a list of strings.

**Comment by pmeric** [comment]
Hi PJ,

I figure you're using an outdated version of the python package, as the latest (12.x) version does not allow a list to be specified for `geo_location `and instead requires a `string`.

The [datasets docs here](https://www.ncbi.nlm.nih.gov/datasets/docs/v1/languages/python/) will be corrected soon. In the meantime, I suggest you update your python requirements in this manner:

`pip install --upgrade "ncbi-datasets-pylib>=12"`

Peter

Peter Meric [C]
Program Principal Engineer
Sequence Enhancements, Tools and Delivery Program, Data Services Division
National Center for Biotechnology Information, NLM, NIH, DHHS

**Comment by DOH-PJG1303** [comment]
Thanks so much for getting back to me so quick!  I'll try that out first thing tomorrow.  

Just to be exactly on the same page, following this upgrade, I should use the string `geo_location = "USA Washington"` to specify that I want to look in Washington State specifically.  Is this correct?

**Comment by DOH-PJG1303** [comment]
Hi Peter (@pmeric ),
I followed your instructions to download the most up to date version (thank you!) and am now no longer able to pass in that geo_location as a list.  Awesome.  However, now that it needs to be 1 string, I can't seem to find out the correct format for specifying Washington (see comment above for example of 1 of the many I've tried).  How would I go about doing this?  

Side note: the taxon argument is now read in as a string.  As someone who followed the [jupyter markdown tutorial](https://github.com/ncbi/datasets/tree/master/examples/jupyter), which was extremely helpful btw, this variable was initially presented as an integer.

**Comment by pmeric** [comment]
Hi PJ,

You should simply specify `geo_location="WA"`.

(We made a backend fix just this afternoon -- there had been been a shortcoming that prevented this from working as one might have expected. In case you've already tried "WA", please try again.)

Using the datasets CLI tools, I just ran the following download and confirmed that there are about 38K sars2 genomes from WA available at present.

```
> datasets download virus genome taxon sars-cov-2 --geo-location wa --exclude-cds --exclude-gpff --exclude-pdb --exclude-protein --exclude-seq --filename sars2_WA.zip
Downloading: sars2_WA.zip    96.9MB done

> dataformat --package sars2_WA_prod.zip  tsv virus-genome |wc -l
37930
```

**Comment by DOH-PJG1303** [comment]
Hi Peter,

I hit an error where the object downloaded when I specified `geo_location="WA"` had "no data attribute".  I upgraded the package as well before performing this action.  Below is a screenshot of the error.
<img width="384" alt="image" src="https://user-images.githubusercontent.com/80795761/145283589-ee9406f8-967b-4dec-b65d-0d2d87247bd3.png">

And here is a peak at the code (mostly copied from the jupyter example) that I used to define the object
<img width="419" alt="image" src="https://user-images.githubusercontent.com/80795761/145283673-c3550fc1-8135-4568-af2a-dff269fb0507.png">

**Comment by pmeric** [comment]
Adding `_preload_content=False` to the argument list for `virus_genome_download()` will avoid this particular error.

The example python code is [in our docs here](https://www.ncbi.nlm.nih.gov/datasets/docs/v1/how-tos/virus/get-sars2-genomes/).
