### ISSUE TITLE
Dataformat tsv outputs shifted rows when tab characters are in assembly metadata

### ISSUE THREAD

**Issue by marco-mariotti** [ncbi/datasets#85]
I ran into this problem: some assembly metadata contains tab characters. Though it probably shouldn't, dataformat should take care of removing or replacing any such characters. Currently, the output table is shifted.

Here's how to reproduce the problem (with accession GCA_012365135.1)

1.Download metadata only
`datasets download genome accession GCA_012365135.1 --dehydrated --filename  bug.zip`

2.Reformat to tsv
`dataformat tsv genome --package bug.zip --fields tax-id,assminfo-bioproject-lineage-title,assminfo-accession > out.tsv`

3. Visualize tab characters
`sed 's/\t/ **** /g'  out.tsv`

**Comment by ericcox1** [comment]
Hi marco-mariotti,

Thanks for your feedback. I have shared this with our development team and we will try to get this fixed soon. I'll post an update to this issue when we have a fix ready.

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
eric.cox@nih.gov

**Comment by pmeric** [comment]
Hi Marco,

We released a fix overnight in our backends to normalize the whitespace in BioProject titles.

If you download the package again (`datasets download...`), you will find that the `dataformat` output no longer contains tab chars within the `assminfo-bioproject-lineage-title` field.

Thanks for reporting.

Peter

Peter Meric [C]
Program Principal Engineer
Sequence Enhancements, Tools and Delivery Program, Data Services Division
National Center for Biotechnology Information, NLM, NIH, DHHS
