### ISSUE TITLE
Very slow download speeds + corrupted .zip files

### ISSUE THREAD

**Issue by RomFas** [ncbi/datasets#93]
Hi, thanks for the great tool!

I have been having some issues with downloading SARS-CoV-2 protein sequences lately. Specifically, I am interested in the N protein (although some ORFs could also be useful). When I try to get those .faa files (either from the NCBI website, the command line tool, or the ncbi datasets python package), I am getting very slow downloading speeds. 

Specifically, for the N protein, I am getting an average download of 35KB/s, tested on different machines and networks. Even for sequences that were released since last December, this could take up to 30 minutes in total. When I also include other proteins, the downloading speeds do seem to increase a bit, but most of the times, even the .zip file that I am getting is corrupt (tested through the website), and the files cannot even be extracted (this does seem to be random).

Is this something temporary or these are the downloading speeds that I should be expecting? (I remember using the tool in the past, and downloads seemed to be much faster than this).  Is there a recommended way to increase the download speed? I also tried Aspera Connect which is actually recommended from NCBI, but this didn't work any better.

Thanks!

**Comment by pmeric** [comment]
Hi RomFas,

I might assume from your message that you're retrieving SARS-CoV-2 protein packages for N specifically? It would help us to know specifically the tool you're using to download (eg. web app, OpenAPI, public url endpoints, language-specific API, datasets CLI tool), and the arguments/flags you're specifying.

Likelihood of corrupt downloads is somewhat proportional to the duration of the download. That said, there are certain combinations of download arguments that are going to be significantly faster (and therefore, less prone to corruption) than others. In general, downloading "all" (ie. without limiting the date range) SARS-CoV-2 datasets will be necessary to achieve high retrieval throughput. Even if you're only interested in a single protein, I might suggest that retrieving all complete genomes will be the fastest route to success. We acknowledge both of these suggestions have obvious downsides from a user's perspective, the upside being fast download times and probability of a successful download.

Note: the datasets platform does not support the aspera protocol.

Regards,
Peter

Peter Meric [C]
Program Principal Engineer
Sequence Enhancements, Tools and Delivery Program, Data Services Division
National Center for Biotechnology Information, NLM, NIH, DHHS

**Comment by RomFas** [comment]
Hi pmeric, 

The average documented download speeds that I mentioned are measured from the web tool (https://www.ncbi.nlm.nih.gov/datasets/coronavirus/proteins/). Using the web tool, I do get corrupted .zip most of the time, using different arguments each time.  While I haven't done specific measurements for other tools, using the latest version of ncbi-datasets and using the python virus API, it takes as long to fetch the N proteins, with half the time .zip files being corrupt. 

I understand about getting all the datasets at once. Indeed, that's when downloading speeds are the highest (although the .zip file size also increases by a lot). However, I haven't been able to fetch the whole dataset yet without the .zip file not getting corrupt in the process. Sometimes the download stops around 30 MBs, sometimes at 2 GBs, it's really unpredictable. 

Thanks for the quick answer!

**Comment by ericcox1** [comment]
Hi Romanos, 

I wanted to provide an update on our work to improve delivery of SARS-CoV-2 protein data. You should see faster and more reliable SARS-CoV-2 protein downloads from the SARS-CoV-2 [taxonomy page](https://www.ncbi.nlm.nih.gov/data-hub/taxonomy/2697049/) (Scroll down to find the **Proteins** table), compared to what is available from the Datasets SARS-CoV-2 proteins page. Note that the protein data available from the SARS-CoV-2 taxonomy page is not limited to "complete" genomes, so you will also get larger datasets.

Best,
Eric
