### ISSUE TITLE
"version" argument

### ISSUE THREAD

**Issue by chasemc** [ncbi/datasets#96]
Is it possible to get a command line flag (e.g. `-v- `--version`) to print the tool's version number?

**Comment by ericcox1** [comment]
Hi Chase,

Thanks for the suggestion. You can get the current version using this command:
```
datasets version
12.32.0
```

Best,
Eric

Eric Cox, PhD [Contractor] (he/him/his)
NCBI Datasets
Sequence Enhancements, Tools and Delivery (SeqPlus)
NIH/NLM/NCBI
[eric.cox@nih.gov](mailto:eric.cox@nih.gov)
