### ISSUE TITLE
Advice on downloading large numbers of genomes

### ISSUE THREAD

**Issue by chasemc** [ncbi/datasets#97]
Possibly related to https://github.com/ncbi/datasets/issues/93 but also a question on whether tool is fit for my use.

I'm building a tool that will see us download decently large numbers of genomes at a time (hundreds to thousands) and possibly other labs will try and use the tool as well. I'm currently using [ncbi-genome-download](https://github.com/kblin/ncbi-genome-download) to download genomes, but I'd ideally like to easily download at other taxonomic levels.

I've been playing with the datasets CLI and I'm really liking the data provenance (both the accompanying *.json and *.jsonl) and getting the metadata for genomes in the jsonl is super helpful. 

But I'm having some issues today trying to download queries that result in 100's to 1000's  of genomes.

```
datasets download \
    genome \
    taxon "Pseudomonas" \
    --include-gbff \
    --exclude-genomic-cds --exclude-protein --exclude-rna --exclude-seq \
    --dehydrated
    
Collecting 29,265 genome accessions [================================================] 100% 29265/29265
Downloading: ncbi_dataset.zip    229kB 2.5kB/s
Error: Internal error (invalid zip archive). Please try again
Usage
  datasets download genome taxon <taxon> [flags]
```

I also tried with "Micromonospora" which failed the first time (same error as above) then succeeded a second time. The download step also seems to start high then crash to kB/s as in #93

I have some intermittent failures when downloading specific files from the NCBI FTP on my home internet so it could possibly be that as well.

- Also, is it okay/possible to use datasets to download thousands of genomes; and use from within in a tool?

**Comment by mtntsuchiya** [comment]
Hi chasemc,
Thank you for letting us know of this issue.

NCBI Datasets can be used to download thousands of genomes and the --dehydrate flag is our usual suggestion. However, I was able to reproduce the error you found and we are currently working on a solution. We'll let you know when things improve. 

Thanks again for using NCBI Datasets and please feel free to contact us if you have any other issues. 

Best,
Mirian

Mirian T. N. Tsuchiya, Ph.D.
Bioinformatics Data Wrangler (contractor)
NCBI Datasets (NCBI/NLM/NIH)
(she/her/hers)

**Comment by mtntsuchiya** [comment]
Hi chasemc,
I tried to download the dehydrated packages again today and both downloaded successfully inside and outside the NCBI network. It looks like it was a temporary issue, at least in this case. I also rehydrated both packages successfully, so hopefully, it will all work for you too :)

Please try it again and let us know if you run into any issues. 
Thanks,
Mirian

Mirian T. N. Tsuchiya, Ph.D.
Bioinformatics Data Wrangler (contractor)
NCBI Datasets (NCBI/NLM/NIH)
(she/her/hers)
